# Generated by Django 4.2.23 on 2025-07-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoLaboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_orden', models.DateTimeField(auto_now_add=True)),
                ('fecha_toma_muestra', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('TOMADA', 'Muestra Tomada'), ('PROCESANDO', 'Procesando'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('es_imagen', models.BooleanField(default=False, help_text='Indica si este tipo de examen es una imagen diagnóstica')),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_resultado', models.DateTimeField(auto_now_add=True)),
                ('resultado_texto', models.TextField(blank=True, help_text='Resultados textuales del examen', null=True)),
                ('archivo_resultado', models.FileField(blank=True, help_text='Archivo del resultado (PDF, JPG, DICOM, etc.)', null=True, upload_to='resultados_laboratorio/')),
                ('validado', models.BooleanField(default=False)),
                ('equipo_utilizado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados', to='laboratories.equipolaboratorio')),
                ('orden_examen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='laboratories.ordenexamen')),
                ('profesional_responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resultados_emitidos', to='professionals.profesionalsalud')),
            ],
        ),
    ]
