# Generated by Django 4.2.23 on 2025-07-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medical_records', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        ('laboratories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenexamen',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_examen', to='medical_records.consulta'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_examen', to='patients.paciente'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='profesional_solicitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_solicitadas', to='professionals.profesionalsalud'),
        ),
        migrations.AddField(
            model_name='ordenexamen',
            name='tipo_examen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes', to='laboratories.tipoexamen'),
        ),
    ]
