# Generated by Django 4.2.23 on 2025-07-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('total_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_neto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('VALIDADA_DIAN', 'Validada por DIAN'), ('ANULADA', 'Anulada'), ('PAGADA', 'Pagada')], default='BORRADOR', max_length=20)),
                ('cufe', models.CharField(blank=True, help_text='Código Único de Factura Electrónica', max_length=100, null=True, unique=True)),
                ('uuid', models.CharField(blank=True, help_text='Universal Unique Identifier para facturación electrónica', max_length=100, null=True, unique=True)),
                ('xml_dian', models.FileField(blank=True, help_text='XML de la factura enviado a la DIAN', null=True, upload_to='facturas_xml/')),
                ('pdf_factura', models.FileField(blank=True, help_text='PDF de la representación gráfica de la factura', null=True, upload_to='facturas_pdf/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='facturas_qr/')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas', to='patients.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TransaccionDIAN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('tipo_transaccion', models.CharField(help_text='Ej: SendBillAsync, GetStatusCufe', max_length=50)),
                ('request_payload', models.TextField(blank=True, null=True)),
                ('response_payload', models.TextField(blank=True, null=True)),
                ('estado_respuesta', models.CharField(blank=True, help_text='Ej: Aceptado, Rechazado, Pendiente', max_length=50, null=True)),
                ('mensaje_error', models.TextField(blank=True, null=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_dian', to='billing.factura')),
            ],
            options={
                'verbose_name': 'Transacción DIAN',
                'verbose_name_plural': 'Transacciones DIAN',
            },
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del ítem facturado, si no es un producto del inventario.', null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_linea', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='billing.factura')),
            ],
            options={
                'verbose_name': 'Detalle de Factura',
                'verbose_name_plural': 'Detalles de Factura',
            },
        ),
    ]
