# Generated by Django 4.2.23 on 2025-07-12 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acs_hms_base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Drug Name')),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Generic Name')),
                ('brand_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Brand Name')),
                ('drug_type', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injection'), ('CREAM', 'Cream'), ('OINTMENT', 'Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SPRAY', 'Spray'), ('POWDER', 'Powder'), ('SOLUTION', 'Solution'), ('SUSPENSION', 'Suspension')], max_length=20, verbose_name='Drug Type')),
                ('strength', models.CharField(max_length=50, verbose_name='Strength')),
                ('unit', models.CharField(max_length=20, verbose_name='Unit')),
                ('schedule', models.CharField(choices=[('H', 'Schedule H'), ('H1', 'Schedule H1'), ('X', 'Schedule X'), ('G', 'Schedule G'), ('OTC', 'Over The Counter')], max_length=10, verbose_name='Schedule')),
                ('drug_license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Drug License Number')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='MRP')),
                ('minimum_stock', models.PositiveIntegerField(default=10, verbose_name='Minimum Stock Level')),
                ('maximum_stock', models.PositiveIntegerField(default=1000, verbose_name='Maximum Stock Level')),
                ('indications', models.TextField(blank=True, null=True, verbose_name='Indications')),
                ('contraindications', models.TextField(blank=True, null=True, verbose_name='Contraindications')),
                ('side_effects', models.TextField(blank=True, null=True, verbose_name='Side Effects')),
                ('dosage_instructions', models.TextField(blank=True, null=True, verbose_name='Dosage Instructions')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Drug',
                'verbose_name_plural': 'Drugs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Drug Category',
                'verbose_name_plural': 'Drug Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DrugInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(max_length=50, verbose_name='Batch Number')),
                ('manufacturing_date', models.DateField(verbose_name='Manufacturing Date')),
                ('expiry_date', models.DateField(verbose_name='Expiry Date')),
                ('received_quantity', models.PositiveIntegerField(verbose_name='Received Quantity')),
                ('current_stock', models.PositiveIntegerField(verbose_name='Current Stock')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Purchase Price')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Selling Price')),
                ('supplier', models.CharField(max_length=100, verbose_name='Supplier')),
                ('purchase_order_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Purchase Order Number')),
                ('received_date', models.DateField(verbose_name='Received Date')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='acs_hms_pharmacy.drug')),
            ],
            options={
                'verbose_name': 'Drug Inventory',
                'verbose_name_plural': 'Drug Inventories',
                'ordering': ['expiry_date'],
                'unique_together': {('drug', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Manufacturer Name')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('license_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='License Number')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Manufacturer',
                'verbose_name_plural': 'Manufacturers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prescription_number', models.CharField(max_length=20, unique=True, verbose_name='Prescription Number')),
                ('prescription_date', models.DateField(verbose_name='Prescription Date')),
                ('diagnosis', models.TextField(blank=True, null=True, verbose_name='Diagnosis')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='Status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount')),
                ('insurance_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Insurance Coverage')),
                ('patient_payable', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Patient Payable')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='acs_hms_base.hmsuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='acs_hms_base.patient')),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'ordering': ['-prescription_date'],
            },
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=50, verbose_name='Dosage')),
                ('frequency', models.CharField(max_length=50, verbose_name='Frequency')),
                ('duration', models.CharField(max_length=50, verbose_name='Duration')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('quantity_prescribed', models.PositiveIntegerField(verbose_name='Quantity Prescribed')),
                ('quantity_dispensed', models.PositiveIntegerField(default=0, verbose_name='Quantity Dispensed')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIALLY_DISPENSED', 'Partially Dispensed'), ('DISPENSED', 'Dispensed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='Status')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription_items', to='acs_hms_pharmacy.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='acs_hms_pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Prescription Item',
                'verbose_name_plural': 'Prescription Items',
            },
        ),
        migrations.CreateModel(
            name='PharmacyStockAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjustment_type', models.CharField(choices=[('INCREASE', 'Stock Increase'), ('DECREASE', 'Stock Decrease'), ('DAMAGE', 'Damage'), ('EXPIRED', 'Expired'), ('LOST', 'Lost'), ('RETURN', 'Return')], max_length=20, verbose_name='Adjustment Type')),
                ('quantity', models.IntegerField(verbose_name='Quantity')),
                ('reason', models.TextField(verbose_name='Reason')),
                ('adjustment_date', models.DateTimeField(auto_now_add=True, verbose_name='Adjustment Date')),
                ('adjusted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_adjustments', to='acs_hms_base.hmsuser')),
                ('drug_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='acs_hms_pharmacy.druginventory')),
            ],
            options={
                'verbose_name': 'Stock Adjustment',
                'verbose_name_plural': 'Stock Adjustments',
                'ordering': ['-adjustment_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_tax', models.BooleanField(default=True, verbose_name='Enable Tax')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Tax Rate (%)')),
                ('low_stock_alert_days', models.PositiveIntegerField(default=30, verbose_name='Low Stock Alert (Days)')),
                ('expiry_alert_days', models.PositiveIntegerField(default=90, verbose_name='Expiry Alert (Days)')),
                ('prescription_validity_days', models.PositiveIntegerField(default=7, verbose_name='Prescription Validity (Days)')),
                ('allow_partial_dispensing', models.BooleanField(default=True, verbose_name='Allow Partial Dispensing')),
                ('markup_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, verbose_name='Markup Percentage')),
                ('hospital', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_settings', to='acs_hms_base.hospital')),
            ],
            options={
                'verbose_name': 'Pharmacy Settings',
                'verbose_name_plural': 'Pharmacy Settings',
            },
        ),
        migrations.CreateModel(
            name='PharmacyDispensing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispensing_date', models.DateTimeField(verbose_name='Dispensing Date')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('INSURANCE', 'Insurance'), ('CREDIT', 'Credit')], max_length=20, verbose_name='Payment Method')),
                ('receipt_number', models.CharField(max_length=50, unique=True, verbose_name='Receipt Number')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('dispensed_by', models.ForeignKey(limit_choices_to={'user_type': 'PHARMACIST'}, on_delete=django.db.models.deletion.CASCADE, related_name='dispensed_prescriptions', to='acs_hms_base.hmsuser')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_records', to='acs_hms_pharmacy.prescription')),
            ],
            options={
                'verbose_name': 'Pharmacy Dispensing',
                'verbose_name_plural': 'Pharmacy Dispensing',
                'ordering': ['-dispensing_date'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=20, unique=True, verbose_name='Bill Number')),
                ('bill_date', models.DateTimeField(verbose_name='Bill Date')),
                ('bill_type', models.CharField(choices=[('PRESCRIPTION', 'Prescription'), ('OTC', 'Over The Counter'), ('EMERGENCY', 'Emergency')], max_length=20, verbose_name='Bill Type')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Subtotal')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Tax Amount')),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Discount Amount')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Amount')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount Paid')),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('CARD', 'Card'), ('INSURANCE', 'Insurance'), ('CREDIT', 'Credit')], max_length=20, verbose_name='Payment Method')),
                ('insurance_coverage', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Insurance Coverage')),
                ('insurance_claim_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Insurance Claim Number')),
                ('billed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bills', to='acs_hms_base.hmsuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_bills', to='acs_hms_base.patient')),
            ],
            options={
                'verbose_name': 'Pharmacy Billing',
                'verbose_name_plural': 'Pharmacy Billings',
                'ordering': ['-bill_date'],
            },
        ),
        migrations.AddField(
            model_name='drug',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='acs_hms_pharmacy.drugcategory'),
        ),
        migrations.AddField(
            model_name='drug',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs', to='acs_hms_pharmacy.manufacturer'),
        ),
        migrations.CreateModel(
            name='DispensingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_dispensed', models.PositiveIntegerField(verbose_name='Quantity Dispensed')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Unit Price')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total Price')),
                ('dispensing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='acs_hms_pharmacy.pharmacydispensing')),
                ('drug_inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_items', to='acs_hms_pharmacy.druginventory')),
                ('prescription_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispensing_items', to='acs_hms_pharmacy.prescriptionitem')),
            ],
            options={
                'verbose_name': 'Dispensing Item',
                'verbose_name_plural': 'Dispensing Items',
            },
        ),
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('MILD', 'Mild'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe'), ('CONTRAINDICATED', 'Contraindicated')], max_length=20, verbose_name='Severity')),
                ('description', models.TextField(verbose_name='Description')),
                ('clinical_significance', models.TextField(blank=True, null=True, verbose_name='Clinical Significance')),
                ('management', models.TextField(blank=True, null=True, verbose_name='Management')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('drug1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug1', to='acs_hms_pharmacy.drug')),
                ('drug2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions_as_drug2', to='acs_hms_pharmacy.drug')),
            ],
            options={
                'verbose_name': 'Drug Interaction',
                'verbose_name_plural': 'Drug Interactions',
                'unique_together': {('drug1', 'drug2')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='drug',
            unique_together={('name', 'strength', 'manufacturer')},
        ),
    ]
