# Generated by Django 4.2.23 on 2025-07-02 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_auditoria', models.CharField(choices=[('INTERNA', 'Interna'), ('EXTERNA', 'Externa')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('alcance', models.TextField()),
                ('estado', models.CharField(choices=[('PLANIFICADA', 'Planificada'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PLANIFICADA', max_length=20)),
                ('documento_informe', models.FileField(blank=True, null=True, upload_to='auditorias/informes/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('equipo_auditor', models.ManyToManyField(related_name='auditorias_participadas', to='professionals.profesionalsalud')),
            ],
            options={
                'verbose_name': 'Auditoría',
                'verbose_name_plural': 'Auditorías',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='HallazgoAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('clasificacion', models.CharField(help_text='Ej: No Conformidad, Observación, Oportunidad de Mejora', max_length=50)),
                ('evidencia', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite_correccion', models.DateField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='quality_management.auditoria')),
                ('responsable_correccion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hallazgos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hallazgo de Auditoría',
                'verbose_name_plural': 'Hallazgos de Auditoría',
            },
        ),
        migrations.CreateModel(
            name='PlanMejora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_plan', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField()),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_INVESTIGACION', 'En Investigación'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20)),
                ('acciones_implementadas', models.TextField(blank=True, null=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('efectividad', models.CharField(blank=True, help_text='Ej: Efectivo, Parcialmente Efectivo, No Efectivo', max_length=50, null=True)),
                ('hallazgo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_mejora', to='quality_management.hallazgoauditoria')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_mejora_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan de Mejora',
                'verbose_name_plural': 'Planes de Mejora',
            },
        ),
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora_incidente', models.DateTimeField()),
                ('tipo_incidente', models.CharField(choices=[('PACIENTE', 'Incidente con Paciente'), ('PERSONAL', 'Incidente con Personal'), ('INFRAESTRUCTURA', 'Incidente de Infraestructura'), ('EQUIPO', 'Incidente con Equipo'), ('SEGURIDAD', 'Incidente de Seguridad'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('CRITICA', 'Crítica')], default='MEDIA', max_length=10)),
                ('estado', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_INVESTIGACION', 'En Investigación'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='REPORTADO', max_length=20)),
                ('fecha_hora_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('acciones_correctivas', models.TextField(blank=True, null=True)),
                ('investigador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_investigados', to='professionals.profesionalsalud')),
                ('paciente_afectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_afectados', to='patients.paciente')),
                ('reportado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ['fecha_hora_incidente'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('tipo_documento', models.CharField(choices=[('MANUAL', 'Manual'), ('PROCEDIMIENTO', 'Procedimiento'), ('POLITICA', 'Política'), ('FORMATO', 'Formato'), ('GUIA', 'Guía'), ('REGISTRO', 'Registro'), ('OTRO', 'Otro')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('fecha_revision', models.DateField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='documentos_calidad/')),
                ('activo', models.BooleanField(default=True)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_aprobados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento de Calidad',
                'verbose_name_plural': 'Documentos de Calidad',
                'ordering': ['-fecha_emision'],
            },
        ),
    ]
