# Generated by Django 4.2.23 on 2025-07-02 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('codigo_activo', models.CharField(blank=True, help_text='Código interno del activo', max_length=50, null=True, unique=True)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_adquisicion', models.DateField()),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vida_util_anios', models.IntegerField(blank=True, help_text='Vida útil esperada en años', null=True)),
                ('ubicacion_actual', models.CharField(blank=True, help_text='Ej: Área de Radiología, Oficina 305', max_length=255, null=True)),
                ('estado', models.CharField(choices=[('OPERATIVO', 'Operativo'), ('MANTENIMIENTO', 'En Mantenimiento'), ('BAJA', 'Dado de Baja'), ('OBSOLETO', 'Obsoleto')], default='OPERATIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Activo Fijo',
                'verbose_name_plural': 'Activos Fijos',
            },
        ),
        migrations.CreateModel(
            name='CategoriaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Categoría de Activo',
                'verbose_name_plural': 'Categorías de Activos',
            },
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('PREVENTIVO', 'Preventivo'), ('CORRECTIVO', 'Correctivo'), ('PREDICTIVO', 'Predictivo')], max_length=20)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descripcion_problema', models.TextField(blank=True, null=True)),
                ('acciones_realizadas', models.TextField()),
                ('responsable_mantenimiento', models.CharField(blank=True, help_text='Persona o empresa que realizó el mantenimiento', max_length=100, null=True)),
                ('proximo_mantenimiento_sugerido', models.DateField(blank=True, null=True)),
                ('activo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='asset_management.activofijo')),
            ],
            options={
                'verbose_name': 'Mantenimiento',
                'verbose_name_plural': 'Mantenimientos',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='BajaActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_baja', models.DateField(auto_now_add=True)),
                ('razon_baja', models.TextField()),
                ('valor_residual', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baja', to='asset_management.activofijo')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bajas_aprobadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Baja de Activo',
                'verbose_name_plural': 'Bajas de Activos',
            },
        ),
        migrations.AddField(
            model_name='activofijo',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos', to='asset_management.categoriaactivo'),
        ),
        migrations.AddField(
            model_name='activofijo',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable del activo', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activos_a_cargo', to=settings.AUTH_USER_MODEL),
        ),
    ]
