# Generated by Django 4.2.23 on 2025-08-10 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acs_hms_base', '0001_initial'),
        ('acs_hms_online_appointment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaElectronicaDisponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_desde', models.DateField(help_text='Fecha de inicio de la disponibilidad')),
                ('fecha_hasta', models.DateField(help_text='Fecha de fin de la disponibilidad')),
                ('hora_inicio_am', models.TimeField(blank=True, help_text='Hora de inicio turno mañana', null=True)),
                ('hora_fin_am', models.TimeField(blank=True, help_text='Hora de fin turno mañana', null=True)),
                ('hora_inicio_pm', models.TimeField(blank=True, help_text='Hora de inicio turno tarde', null=True)),
                ('hora_fin_pm', models.TimeField(blank=True, help_text='Hora de fin turno tarde', null=True)),
                ('dividir_en', models.IntegerField(default=30, help_text='Duración de cada cita en minutos')),
                ('sede', models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('SUCURSAL_1', 'SUCURSAL 1'), ('SUCURSAL_2', 'SUCURSAL 2'), ('CONSULTORIO_EXTERNO', 'CONSULTORIO EXTERNO')], default='PRINCIPAL', help_text='Sede donde se creará la disponibilidad', max_length=50)),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
                ('sabado', models.BooleanField(default=False)),
                ('domingo', models.BooleanField(default=False)),
                ('habilitar_agenda_tus_citas', models.BooleanField(default=False)),
                ('habilitar_doctoralia', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('inactive', 'Inactiva'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('slots_generados', models.IntegerField(default=0, help_text='Cantidad de slots generados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agenda_creadas', to=settings.AUTH_USER_MODEL)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_disponibilidades', to='acs_hms_base.hmsuser')),
            ],
            options={
                'verbose_name': 'Agenda Electrónica Disponibilidad',
                'verbose_name_plural': 'Agenda Electrónica Disponibilidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='habilitar_agenda_tus_citas',
            field=models.BooleanField(default=False, help_text='Habilitar en plataforma Agenda tus citas'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='habilitar_doctoralia',
            field=models.BooleanField(default=False, help_text='Habilitar en plataforma Doctoralia'),
        ),
        migrations.AddField(
            model_name='doctoravailability',
            name='sede',
            field=models.CharField(choices=[('PRINCIPAL', 'PRINCIPAL'), ('SUCURSAL_1', 'SUCURSAL 1'), ('SUCURSAL_2', 'SUCURSAL 2'), ('CONSULTORIO_EXTERNO', 'CONSULTORIO EXTERNO')], default='PRINCIPAL', max_length=50),
        ),
        migrations.CreateModel(
            name='DisponibilidadDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_disponibilidad', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_terminacion', models.TimeField()),
                ('agenda_tus_citas', models.BooleanField(default=False)),
                ('doctoralia', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_booked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agenda_disponibilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='acs_hms_online_appointment.agendaelectronicadisponibilidad')),
            ],
            options={
                'verbose_name': 'Detalle de Disponibilidad',
                'verbose_name_plural': 'Detalles de Disponibilidad',
                'ordering': ['fecha_disponibilidad', 'hora_inicio'],
            },
        ),
    ]
