# Generated by Django 4.2.23 on 2025-08-10 06:10

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('fecha_validez', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('RECIBIDA', 'Recibida'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cotización de Compra',
                'verbose_name_plural': 'Cotizaciones de Compra',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCotizacionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.cotizacioncompra')),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotizaciones',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Compra',
                'verbose_name_plural': 'Detalles de Facturas de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Compra',
                'verbose_name_plural': 'Detalles de Órdenes de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_esperada', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField()),
                ('cantidad_rechazada', models.IntegerField(default=0)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle de Recepción',
                'verbose_name_plural': 'Detalles de Recepciones',
            },
        ),
        migrations.CreateModel(
            name='FacturaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('RECIBIDA', 'Recibida'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Factura de Compra',
                'verbose_name_plural': 'Facturas de Compra',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('fecha_orden', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega_esperada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDA', 'Recibida'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.CreateModel(
            name='PagoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='purchases.facturacompra')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pagos de Compra',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('MEDICAMENTOS', 'Medicamentos'), ('EQUIPOS', 'Equipos Médicos'), ('INSUMOS', 'Insumos'), ('ALIMENTOS', 'Alimentos'), ('LIMPEZA', 'Limpieza'), ('OFICINA', 'Oficina'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('unidad_medida', models.CharField(default='UNIDAD', max_length=20)),
                ('precio_estimado', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('stock_minimo', models.IntegerField(default=0)),
                ('stock_actual', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto de Compra',
                'verbose_name_plural': 'Productos de Compra',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='purchases.ordencompra')),
                ('recibido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recepción de Compra',
                'verbose_name_plural': 'Recepciones de Compra',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderline',
            name='purchase_order',
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RenameField(
            model_name='proveedor',
            old_name='created_at',
            new_name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='address',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='calificacion',
            field=models.IntegerField(default=5, help_text='Calificación del 1 al 5'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_principal',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='identificacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='limite_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='saldo_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='terminos_pago',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(choices=[('MEDICAMENTOS', 'Medicamentos'), ('EQUIPOS', 'Equipos Médicos'), ('INSUMOS', 'Insumos'), ('SERVICIOS', 'Servicios'), ('ALIMENTOS', 'Alimentos'), ('OTROS', 'Otros')], default='OTROS', max_length=20),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderLine',
        ),
        migrations.AddField(
            model_name='productocompra',
            name='proveedores_preferidos',
            field=models.ManyToManyField(blank=True, related_name='productos_preferidos', to='purchases.proveedor'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_compra', to='purchases.proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='orden_compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='purchases.ordencompra'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas_compra', to='purchases.proveedor'),
        ),
        migrations.AddField(
            model_name='facturacompra',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_recibidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detallerecepcioncompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.productocompra'),
        ),
        migrations.AddField(
            model_name='detallerecepcioncompra',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.recepcioncompra'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.ordencompra'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.productocompra'),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='purchases.facturacompra'),
        ),
        migrations.AddField(
            model_name='detallefacturacompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.productocompra'),
        ),
        migrations.AddField(
            model_name='detallecotizacioncompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchases.productocompra'),
        ),
        migrations.AddField(
            model_name='cotizacioncompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='purchases.proveedor'),
        ),
        migrations.AddField(
            model_name='cotizacioncompra',
            name='solicitado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='facturacompra',
            unique_together={('numero_factura', 'proveedor')},
        ),
    ]
