# Generated by Django 4.2.23 on 2025-08-10 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Convenio')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de Fin')),
                ('valor_contrato', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor del Contrato')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido'), ('VENCIDO', 'Vencido')], default='ACTIVO', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Convenio',
                'verbose_name_plural': 'Convenios',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('tipo_empresa', models.CharField(choices=[('EPS', 'EPS'), ('ARL', 'ARL'), ('AFP', 'AFP'), ('EMPRESA', 'Empresa'), ('COOPERATIVA', 'Cooperativa'), ('FUNDACION', 'Fundación'), ('OTRO', 'Otro')], default='EMPRESA', max_length=20, verbose_name='Tipo de Empresa')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('contacto_principal', models.CharField(blank=True, max_length=100, verbose_name='Contacto Principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('pais', models.CharField(default='COLOMBIA', max_length=50, verbose_name='País')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['departamento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='OrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N°. O.S.')),
                ('fecha_orden', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('estado_orden', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('AUTORIZADA', 'Autorizada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada'), ('FACTURADA', 'Facturada')], default='PENDIENTE', max_length=20, verbose_name='Estado')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('MS', 'Menor sin Identificación'), ('AS', 'Adulto sin Identificación')], default='CC', max_length=10, verbose_name='Tipo')),
                ('numero_identificacion', models.CharField(max_length=20, verbose_name='N°. de Identificación')),
                ('ciudad_nacimiento', models.CharField(blank=True, max_length=100, verbose_name='Ciudad de Nacimiento')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('primer_apellido', models.CharField(max_length=50, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, verbose_name='Segundo Apellido')),
                ('primer_nombre', models.CharField(max_length=50, verbose_name='Primer Nombre')),
                ('otros_nombres', models.CharField(blank=True, max_length=100, verbose_name='Otros Nombres')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('estado_civil', models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('UNION_LIBRE', 'Unión Libre'), ('DIVORCIADO', 'Divorciado'), ('VIUDO', 'Viudo'), ('OTRO', 'Otro')], max_length=20, verbose_name='Estado Civil')),
                ('nivel_educativo', models.CharField(choices=[('NINGUNO', 'Ninguno'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Técnico'), ('TECNOLOGO', 'Tecnólogo'), ('PROFESIONAL', 'Profesional'), ('ESPECIALIZACION', 'Especialización'), ('MAESTRIA', 'Maestría'), ('DOCTORADO', 'Doctorado')], max_length=20, verbose_name='Nivel Educativo')),
                ('correo_electronico', models.EmailField(blank=True, max_length=254, verbose_name='Correo Electrónico')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ordenes/fotos/', verbose_name='Foto')),
                ('huella', models.ImageField(blank=True, null=True, upload_to='ordenes/huellas/', verbose_name='Huella')),
                ('firma', models.ImageField(blank=True, null=True, upload_to='ordenes/firmas/', verbose_name='Firma')),
                ('zona', models.CharField(choices=[('URBANA', 'Urbana'), ('RURAL', 'Rural')], default='URBANA', max_length=10, verbose_name='Zona')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('barrio', models.CharField(blank=True, max_length=100, verbose_name='Barrio')),
                ('localidad', models.CharField(blank=True, max_length=100, verbose_name='Localidad')),
                ('sede', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SUCURSAL_1', 'Sucursal 1'), ('SUCURSAL_2', 'Sucursal 2'), ('CONSULTORIO_EXTERNO', 'Consultorio Externo')], default='PRINCIPAL', max_length=50, verbose_name='Sede')),
                ('estrato', models.CharField(choices=[('1', 'Estrato 1'), ('2', 'Estrato 2'), ('3', 'Estrato 3'), ('4', 'Estrato 4'), ('5', 'Estrato 5'), ('6', 'Estrato 6')], max_length=1, verbose_name='Estrato')),
                ('celulares', models.CharField(blank=True, max_length=50, verbose_name='Celulares')),
                ('telefonos', models.CharField(blank=True, max_length=50, verbose_name='Teléfonos')),
                ('profesion_cargo', models.CharField(max_length=100, verbose_name='Profesión o Cargo')),
                ('funciones_cargo', models.TextField(blank=True, verbose_name='Funciones del Cargo')),
                ('tipo_evaluacion', models.CharField(max_length=200, verbose_name='Tipo de Evaluación Médica o Procedimiento')),
                ('eps', models.CharField(blank=True, max_length=100, verbose_name='EPS')),
                ('afp', models.CharField(blank=True, max_length=100, verbose_name='AFP')),
                ('arl', models.CharField(blank=True, max_length=100, verbose_name='ARL')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones, N° de Autorización o Solicitud')),
                ('fecha_solicitud', models.DateField(verbose_name='Fecha de Solicitud')),
                ('total_orden', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total de la Orden Servicios')),
                ('total_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total a Pagar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision_recepcion.convenio', verbose_name='Acuerdo Comercial, Contrato o Convenio')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa_mision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mision', to='admision_recepcion.empresa', verbose_name='Empresa en Misión')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision_recepcion.municipio', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Orden de Servicio',
                'verbose_name_plural': 'Órdenes de Servicios',
                'ordering': ['-fecha_orden', '-numero_orden'],
            },
        ),
        migrations.CreateModel(
            name='Prestador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('tipo', models.CharField(default='MEDICO', max_length=50, verbose_name='Tipo')),
                ('especialidad', models.CharField(blank=True, max_length=100, verbose_name='Especialidad')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Prestador',
                'verbose_name_plural': 'Prestadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('CONSULTA', 'Consulta'), ('EXAMEN', 'Examen'), ('PROCEDIMIENTO', 'Procedimiento'), ('CIRUGIA', 'Cirugía'), ('TERAPIA', 'Terapia'), ('MEDICAMENTO', 'Medicamento'), ('MATERIAL', 'Material'), ('OTRO', 'Otro')], default='CONSULTA', max_length=20, verbose_name='Tipo')),
                ('valor_base', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Base')),
                ('requiere_autorizacion', models.BooleanField(default=False, verbose_name='Requiere Autorización')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='SeguimientoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_ATENCION', 'En Atención'), ('EN_ESPERA', 'En Espera'), ('ATENDIDO', 'Atendido'), ('ALTA', 'Alta'), ('REMITIDO', 'Remitido')], default='INGRESADO', max_length=20)),
                ('fecha_estado', models.DateTimeField(default=django.utils.timezone.now)),
                ('observaciones', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='admision_recepcion.ordenservicio')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Seguimiento de Paciente',
                'verbose_name_plural': 'Seguimientos de Pacientes',
                'ordering': ['-fecha_estado'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vr. Unitario')),
                ('forma_pago', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('CONVENIO', 'Convenio'), ('SEGURO', 'Seguro'), ('MIXTO', 'Mixto')], default='CONTADO', max_length=20, verbose_name='Forma de Pago')),
                ('valor_pagar', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Vr. Pagar')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('autorizado', models.BooleanField(default=False, verbose_name='Autorizado')),
                ('numero_autorizacion', models.CharField(blank=True, max_length=50, verbose_name='N° Autorización')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='admision_recepcion.ordenservicio', verbose_name='Orden')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision_recepcion.prestador', verbose_name='Prestador del Servicio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admision_recepcion.servicio', verbose_name='Producto o Servicio')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Servicio',
                'verbose_name_plural': 'Detalles de Órdenes de Servicios',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='convenio',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convenios', to='admision_recepcion.empresa', verbose_name='Empresa'),
        ),
    ]
