# Generated by Django 4.2.23 on 2025-08-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admision_recepcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimientopaciente',
            name='estado',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_ESPERA', 'En Espera'), ('EN_ATENCION', 'En Atención'), ('ATENDIDO', 'Atendido'), ('ALTA', 'Alta'), ('REMITIDO', 'Remitido'), ('CANCELADO', 'Cancelado')], default='INGRESADO', max_length=20),
        ),
    ]
