# Generated by Django 4.2.23 on 2025-08-10 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admision_recepcion', '0002_alter_seguimientopaciente_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cita', models.CharField(blank=True, max_length=20, unique=True, verbose_name='N° Cita')),
                ('fecha_cita', models.DateField(verbose_name='Día de la Cita')),
                ('hora_cita', models.TimeField(verbose_name='Hora de la Cita')),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CONFIRMADA', 'Confirmada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('COMPLETADA', 'Completada'), ('NO_ASISTIO', 'No Asistió')], default='PROGRAMADA', max_length=20, verbose_name='Estado')),
                ('numero_identificacion', models.CharField(max_length=20, verbose_name='N°. de Identificación')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('MS', 'Menor sin Identificación'), ('AS', 'Adulto sin Identificación')], default='CC', max_length=10, verbose_name='Tipo Documento')),
                ('nombre_trabajador', models.CharField(max_length=200, verbose_name='Nombre del Trabajador')),
                ('telefono_trabajador', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email_trabajador', models.EmailField(blank=True, max_length=254, verbose_name='Email Trabajador')),
                ('contacto_empresa', models.CharField(blank=True, max_length=100, verbose_name='Contacto en la Empresa')),
                ('telefono_empresa', models.CharField(blank=True, max_length=20, verbose_name='Teléfono Empresa')),
                ('email_empresa', models.EmailField(blank=True, max_length=254, verbose_name='Email Empresa')),
                ('tipo_servicio', models.CharField(choices=[('EXAMEN_INGRESO', 'Examen de Ingreso'), ('EXAMEN_PERIODICO', 'Examen Periódico'), ('EXAMEN_RETIRO', 'Examen de Retiro'), ('EXAMEN_REINTEGRO', 'Examen de Reintegro'), ('CONSULTA_MEDICINA', 'Consulta Medicina General'), ('EXAMEN_ALTURA', 'Examen Trabajo en Alturas'), ('EXAMEN_ESPACIOS', 'Examen Espacios Confinados'), ('AUDIOMETRIA', 'Audiometría'), ('VISIOMETRIA', 'Visiometría'), ('LABORATORIO', 'Laboratorio Clínico'), ('ELECTROCARDIOGRAMA', 'Electrocardiograma'), ('RADIOGRAFIA', 'Radiografía')], max_length=30, verbose_name='Tipo de Servicio')),
                ('observaciones_servicio', models.TextField(blank=True, verbose_name='Observaciones del Servicio')),
                ('sede_cita', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('SUCURSAL_1', 'Sucursal 1'), ('SUCURSAL_2', 'Sucursal 2'), ('CONSULTORIO_EXTERNO', 'Consultorio Externo')], default='PRINCIPAL', max_length=50, verbose_name='Sede de la Cita')),
                ('fecha_programacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Programación')),
                ('programada_por_portal', models.BooleanField(default=True, verbose_name='Programada por Portal')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de Origen')),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Confirmación')),
                ('fecha_cancelacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cancelación')),
                ('motivo_cancelacion', models.TextField(blank=True, verbose_name='Motivo de Cancelación')),
                ('requiere_autorizacion', models.BooleanField(default=False, verbose_name='Requiere Autorización')),
                ('numero_autorizacion', models.CharField(blank=True, max_length=50, verbose_name='N° Autorización')),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Valor Estimado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_canceladas', to=settings.AUTH_USER_MODEL, verbose_name='Cancelada Por')),
                ('confirmada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_confirmadas', to=settings.AUTH_USER_MODEL, verbose_name='Confirmada Por')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_portal', to='admision_recepcion.empresa', verbose_name='Empresa')),
                ('orden_servicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cita_empresarial', to='admision_recepcion.ordenservicio', verbose_name='Orden de Servicio')),
                ('prestador_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision_recepcion.prestador', verbose_name='Prestador Asignado')),
                ('servicios_adicionales', models.ManyToManyField(blank=True, to='admision_recepcion.servicio', verbose_name='Servicios Adicionales')),
            ],
            options={
                'verbose_name': 'Cita Empresarial',
                'verbose_name_plural': 'Citas Empresariales',
                'ordering': ['-fecha_cita', '-hora_cita'],
                'indexes': [models.Index(fields=['fecha_cita', 'estado'], name='admision_re_fecha_c_9d2baa_idx'), models.Index(fields=['numero_identificacion'], name='admision_re_numero__da4922_idx'), models.Index(fields=['empresa', 'fecha_cita'], name='admision_re_empresa_ec660d_idx')],
            },
        ),
    ]
