# Generated by Django 4.2.23 on 2025-08-10 15:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admision_recepcion', '0003_citaempresarial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Código Interno')),
                ('nombre_producto_servicio', models.CharField(max_length=500, verbose_name='Nombre del Producto o Servicio')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción Detallada')),
                ('categoria', models.CharField(choices=[('LABORATORIO', 'Laboratorio Clínico'), ('IMAGENES', 'Imágenes Diagnósticas'), ('CONSULTAS', 'Consultas Médicas'), ('PROCEDIMIENTOS', 'Procedimientos'), ('MEDICAMENTOS', 'Medicamentos'), ('EXAMENES_OCUPACIONALES', 'Exámenes Ocupacionales'), ('OTROS', 'Otros Servicios'), ('ADMINISTRATIVOS', 'Servicios Administrativos')], default='OTROS', max_length=30, verbose_name='Categoría')),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio')),
                ('precio_convenio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Convenio')),
                ('precio_particular', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio Particular')),
                ('codigo_cups', models.CharField(blank=True, help_text='Código CUPS para RIPS', max_length=20, verbose_name='CUPS')),
                ('codigo_soat', models.CharField(blank=True, max_length=20, verbose_name='Código SOAT')),
                ('codigo_iss', models.CharField(blank=True, max_length=20, verbose_name='Código ISS')),
                ('codigo_cum', models.CharField(blank=True, help_text='Para medicamentos', max_length=20, verbose_name='Código CUM')),
                ('codigo_cie10', models.CharField(blank=True, help_text='Código diagnóstico asociado', max_length=10, verbose_name='CIE-10')),
                ('tipo_rips', models.CharField(blank=True, choices=[('CONSULTA', 'Consulta'), ('PROCEDIMIENTO', 'Procedimiento'), ('OTROS_SERVICIOS', 'Otros Servicios'), ('MEDICAMENTOS', 'Medicamentos'), ('HOSPITALIZACION', 'Hospitalización'), ('URGENCIAS', 'Urgencias'), ('', 'Sin Clasificar')], max_length=20, verbose_name='Tipo RIPS')),
                ('generar_rips', models.BooleanField(default=True, verbose_name='Generar RIPS')),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='IVA (%)')),
                ('gravado_iva', models.BooleanField(default=False, verbose_name='Gravado con IVA')),
                ('precio_por_convenio', models.JSONField(blank=True, default=dict, verbose_name='Precios por Convenio')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('requiere_autorizacion', models.BooleanField(default=False, verbose_name='Requiere Autorización')),
                ('ambulatorio', models.BooleanField(default=True, verbose_name='Ambulatorio')),
                ('hospitalario', models.BooleanField(default=False, verbose_name='Hospitalario')),
                ('unidad_medida', models.CharField(default='Unidad', max_length=50, verbose_name='Unidad de Medida')),
                ('tiempo_estimado', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tiempo Estimado (min)')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('convenios', models.ManyToManyField(blank=True, to='admision_recepcion.convenio', verbose_name='Convenios')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
            ],
            options={
                'verbose_name': 'Lista de Precios',
                'verbose_name_plural': 'Listas de Precios',
                'ordering': ['categoria', 'nombre_producto_servicio'],
                'indexes': [models.Index(fields=['codigo_cups'], name='admision_re_codigo__7b1fc2_idx'), models.Index(fields=['codigo_cum'], name='admision_re_codigo__fff869_idx'), models.Index(fields=['categoria', 'activo'], name='admision_re_categor_4c2153_idx'), models.Index(fields=['nombre_producto_servicio'], name='admision_re_nombre__4be8f5_idx')],
            },
        ),
    ]
