# Generated by Django 4.2.23 on 2025-08-10 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admision_recepcion', '0004_listaprecios'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_hc', models.CharField(max_length=20, unique=True, verbose_name='N° H.C.')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('ANULADA', 'Anulada'), ('EN_PROCESO', 'En Proceso')], default='ABIERTA', max_length=20, verbose_name='Estado')),
                ('numero_identificacion', models.CharField(max_length=20, verbose_name='N°. Identificación')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PA', 'Pasaporte'), ('RC', 'Registro Civil'), ('MS', 'Menor sin Identificación'), ('AS', 'Adulto sin Identificación')], default='CC', max_length=10, verbose_name='Tipo Documento')),
                ('nombre_paciente', models.CharField(max_length=200, verbose_name='Nombre del Paciente')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1, verbose_name='Género')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('tipo_examen', models.CharField(choices=[('EVALUACION_MEDICO_OCUPACIONAL_INGRESO', 'Evaluación Médico Ocupacional de Ingreso'), ('EVALUACION_MEDICO_OCUPACIONAL_PERIODICO', 'Evaluación Médico Ocupacional Periódico'), ('EVALUACION_MEDICO_OCUPACIONAL_RETIRO', 'Evaluación Médico Ocupacional de Retiro'), ('EVALUACION_MEDICO_OCUPACIONAL_REINTEGRO', 'Evaluación Médico Ocupacional de Reintegro'), ('CONSULTA_MEDICINA_GENERAL', 'Consulta Medicina General'), ('CONSULTA_MEDICINA_ESPECIALIZADA', 'Consulta Medicina Especializada'), ('EXAMEN_TRABAJO_ALTURAS', 'Examen Trabajo en Alturas'), ('EXAMEN_ESPACIOS_CONFINADOS', 'Examen Espacios Confinados'), ('AUDIOMETRIA', 'Audiometría'), ('VISIOMETRIA', 'Visiometría'), ('OPTOMETRIA', 'Optometría'), ('PSICOLOGIA_OCUPACIONAL', 'Psicología Ocupacional'), ('OTROS', 'Otros Exámenes')], max_length=50, verbose_name='Tipo de Examen')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de Consulta')),
                ('antecedentes_personales', models.TextField(blank=True, verbose_name='Antecedentes Personales')),
                ('antecedentes_familiares', models.TextField(blank=True, verbose_name='Antecedentes Familiares')),
                ('antecedentes_ocupacionales', models.TextField(blank=True, verbose_name='Antecedentes Ocupacionales')),
                ('revision_sistemas', models.TextField(blank=True, verbose_name='Revisión por Sistemas')),
                ('signos_vitales', models.JSONField(blank=True, default=dict, verbose_name='Signos Vitales')),
                ('examen_fisico', models.TextField(blank=True, verbose_name='Examen Físico')),
                ('laboratorios', models.TextField(blank=True, verbose_name='Resultados de Laboratorio')),
                ('imagenes', models.TextField(blank=True, verbose_name='Resultados de Imágenes')),
                ('otros_examenes', models.TextField(blank=True, verbose_name='Otros Exámenes')),
                ('diagnostico_principal', models.CharField(blank=True, max_length=10, verbose_name='Diagnóstico Principal (CIE-10)')),
                ('diagnosticos_secundarios', models.TextField(blank=True, verbose_name='Diagnósticos Secundarios')),
                ('aptitud_laboral', models.CharField(blank=True, max_length=50, verbose_name='Aptitud Laboral')),
                ('recomendaciones', models.TextField(blank=True, verbose_name='Recomendaciones')),
                ('tratamiento', models.TextField(blank=True, verbose_name='Tratamiento')),
                ('incapacidad_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días de Incapacidad')),
                ('restricciones', models.TextField(blank=True, verbose_name='Restricciones Laborales')),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre')),
                ('motivo_anulacion', models.TextField(blank=True, verbose_name='Motivo de Anulación')),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Anulación')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_anuladas', to=settings.AUTH_USER_MODEL, verbose_name='Anulada Por')),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_cerradas', to=settings.AUTH_USER_MODEL, verbose_name='Cerrada Por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historias_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creado Por')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision_recepcion.empresa', verbose_name='Empresa')),
                ('orden_servicio', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_clinica', to='admision_recepcion.ordenservicio', verbose_name='Orden de Servicio')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision_recepcion.prestador', verbose_name='Profesional')),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-numero_hc'],
                'indexes': [models.Index(fields=['numero_identificacion'], name='admision_re_numero__750bc5_idx'), models.Index(fields=['empresa', 'fecha_creacion'], name='admision_re_empresa_abf0a3_idx'), models.Index(fields=['estado', 'fecha_creacion'], name='admision_re_estado_6ef6e3_idx'), models.Index(fields=['profesional', 'fecha_creacion'], name='admision_re_profesi_9e7437_idx'), models.Index(fields=['tipo_examen'], name='admision_re_tipo_ex_1e9661_idx')],
            },
        ),
    ]
