# Generated by Django 4.2.23 on 2025-08-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admision_recepcion', '0006_evaluacionocupacional_fichaclinica_exposicionlaboral_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamenVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ultimo_examen', models.CharField(blank=True, max_length=200, verbose_name='F. Último Examen')),
                ('lugar_ultimo_examen', models.CharField(blank=True, max_length=200, verbose_name='Lugar del Último Examen')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de Consulta')),
                ('sintomatologia', models.CharField(choices=[('ASINTOMATICO', 'Asintomático'), ('SINTOMATICO', 'Sintomático')], default='ASINTOMATICO', max_length=20, verbose_name='Sintomatología')),
                ('ojo_derecho_vl_sc', models.CharField(blank=True, max_length=10, verbose_name='OD V.L. 20/')),
                ('ojo_derecho_vp_sc', models.CharField(blank=True, max_length=10, verbose_name='OD V.P.')),
                ('ojo_derecho_ph_sc', models.CharField(blank=True, max_length=10, verbose_name='OD PH')),
                ('ojo_izquierdo_vl_sc', models.CharField(blank=True, max_length=10, verbose_name='OI V.L. 20/')),
                ('ojo_izquierdo_vp_sc', models.CharField(blank=True, max_length=10, verbose_name='OI V.P.')),
                ('ojo_izquierdo_ph_sc', models.CharField(blank=True, max_length=10, verbose_name='OI PH')),
                ('ambos_ojos_vl_sc', models.CharField(blank=True, max_length=10, verbose_name='AO V.L. 20/')),
                ('ambos_ojos_vp_sc', models.CharField(blank=True, max_length=10, verbose_name='AO V.P.')),
                ('ambos_ojos_ph_sc', models.CharField(blank=True, max_length=10, verbose_name='AO PH')),
                ('ojo_derecho_vl_cc', models.CharField(blank=True, max_length=10, verbose_name='OD V.L. 20/ (CC)')),
                ('ojo_derecho_vp_cc', models.CharField(blank=True, max_length=10, verbose_name='OD V.P. (CC)')),
                ('ojo_izquierdo_vl_cc', models.CharField(blank=True, max_length=10, verbose_name='OI V.L. 20/ (CC)')),
                ('ojo_izquierdo_vp_cc', models.CharField(blank=True, max_length=10, verbose_name='OI V.P. (CC)')),
                ('ambos_ojos_vl_cc', models.CharField(blank=True, max_length=10, verbose_name='AO V.L. 20/ (CC)')),
                ('ambos_ojos_vp_cc', models.CharField(blank=True, max_length=10, verbose_name='AO V.P. (CC)')),
                ('ojo_derecho_externo', models.TextField(blank=True, verbose_name='Examen Externo OD')),
                ('ojo_izquierdo_externo', models.TextField(blank=True, verbose_name='Examen Externo OI')),
                ('reflejos_observacion', models.CharField(default='PRESENTES Y NORMALES', max_length=100, verbose_name='Reflejos')),
                ('vision_lejana_cover', models.CharField(default='NORMAL', max_length=50, verbose_name='Visión Lejana Cover Test')),
                ('vision_proxima_cover', models.CharField(default='NORMAL', max_length=50, verbose_name='Visión Próxima Cover Test')),
                ('motilidad_observacion', models.CharField(default='NORMAL', max_length=100, verbose_name='Motilidad Ocular')),
                ('convergencia_observacion', models.CharField(default='NORMAL', max_length=100, verbose_name='Punto Próximo de Convergencia')),
                ('ojo_derecho_oftalmoscopia', models.CharField(default='FONDO DE OJO APARENTEMENTE NORMAL', max_length=100, verbose_name='Oftalmoscopía OD')),
                ('ojo_izquierdo_oftalmoscopia', models.CharField(default='FONDO DE OJO APARENTEMENTE NORMAL', max_length=100, verbose_name='Oftalmoscopía OI')),
                ('ojo_derecho_queratometria', models.CharField(blank=True, max_length=20, verbose_name='Queratometría OD K´=')),
                ('ojo_izquierdo_queratometria', models.CharField(blank=True, max_length=20, verbose_name='Queratometría OI K´=')),
                ('ojo_derecho_refraccion_av', models.CharField(blank=True, max_length=10, verbose_name='Refracción OD A.V. 20/')),
                ('ojo_izquierdo_refraccion_av', models.CharField(blank=True, max_length=10, verbose_name='Refracción OI A.V. 20/')),
                ('ojo_derecho_rx_vl', models.CharField(blank=True, max_length=10, verbose_name='RX Final OD V.L. 20/')),
                ('ojo_derecho_rx_vp', models.CharField(blank=True, max_length=10, verbose_name='RX Final OD V.P.')),
                ('ojo_derecho_rx_add', models.CharField(blank=True, max_length=10, verbose_name='RX Final OD ADD')),
                ('ojo_izquierdo_rx_vl', models.CharField(blank=True, max_length=10, verbose_name='RX Final OI V.L. 20/')),
                ('ojo_izquierdo_rx_vp', models.CharField(blank=True, max_length=10, verbose_name='RX Final OI V.P.')),
                ('ojo_izquierdo_rx_add', models.CharField(blank=True, max_length=10, verbose_name='RX Final OI ADD')),
                ('ojo_derecho_vision_color', models.CharField(default='NORMAL', max_length=50, verbose_name='Visión Color OD')),
                ('ojo_izquierdo_vision_color', models.CharField(default='NORMAL', max_length=50, verbose_name='Visión Color OI')),
                ('estereopsis_observacion', models.CharField(default='NORMAL', max_length=100, verbose_name='Estereopsis')),
                ('diagnostico_recomendaciones', models.TextField(blank=True, verbose_name='Diagnóstico y Recomendaciones')),
                ('via_ingreso', models.CharField(default='01', max_length=10, verbose_name='Vía de Ingreso')),
                ('finalidad_consulta', models.CharField(default='15', max_length=10, verbose_name='Finalidad de la Consulta')),
                ('causa_externa', models.CharField(default='38', max_length=10, verbose_name='Causa Externa')),
                ('otras_observaciones', models.TextField(blank=True, verbose_name='Otras Observaciones y Recomendaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_visual', to='admision_recepcion.fichaclinica')),
            ],
            options={
                'verbose_name': 'Examen Visual',
                'verbose_name_plural': 'Exámenes Visuales',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diagnostico', models.CharField(choices=[('PRINCIPAL', 'Diagnóstico Principal'), ('RELACIONADO_1', 'Diagnóstico Relacionado 1'), ('RELACIONADO_2', 'Diagnóstico Relacionado 2'), ('RELACIONADO_3', 'Diagnóstico Relacionado 3')], max_length=20, verbose_name='Tipo de Diagnóstico')),
                ('codigo_cie10', models.CharField(max_length=10, verbose_name='Código CIE10')),
                ('nombre_diagnostico', models.CharField(max_length=200, verbose_name='Nombre del Diagnóstico')),
                ('lateralidad', models.CharField(blank=True, choices=[('', 'Seleccione'), ('BILATERAL', 'Bilateral'), ('DERECHO', 'Derecho'), ('IZQUIERDO', 'Izquierdo'), ('NO_APLICA', 'No Aplica')], max_length=20, verbose_name='Lateralidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tipo_impresion', models.CharField(blank=True, choices=[('IMPRESION_DIAGNOSTICA', 'Impresión Diagnóstica'), ('CONFIRMADO', 'Confirmado'), ('REPETIDO', 'Repetido')], max_length=30, verbose_name='Tipo de Impresión')),
                ('examen_visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_visuales', to='admision_recepcion.examenvisual')),
            ],
            options={
                'verbose_name': 'Diagnóstico Visual',
                'verbose_name_plural': 'Diagnósticos Visuales',
            },
        ),
        migrations.CreateModel(
            name='ConductaRecomendacionVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_item', models.CharField(choices=[('CONDUCTA', 'Conducta'), ('REMISION', 'Remisión')], max_length=20, verbose_name='Tipo')),
                ('codigo', models.CharField(max_length=50, verbose_name='Código')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripción')),
                ('seleccionado', models.BooleanField(default=False, verbose_name='Seleccionado')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('examen_visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductas_recomendaciones', to='admision_recepcion.examenvisual')),
            ],
            options={
                'verbose_name': 'Conducta y Recomendación Visual',
                'verbose_name_plural': 'Conductas y Recomendaciones Visuales',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteVisual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_antecedente', models.CharField(choices=[('ANTECEDENTES_PERSONALES', 'Antecedentes Personales'), ('ANTECEDENTES_FAMILIARES', 'Antecedentes Familiares'), ('ANTECEDENTES_OCUPACIONALES', 'Antecedentes Ocupacionales'), ('EXPOSICION_LABORAL_VISUAL', 'Exposición Laboral Visual'), ('USA_ANTEOJOS', 'Usa Anteojos'), ('MULTIFOCAL', 'Multifocal'), ('LENTES_CONTACTO', 'Lentes de Contacto'), ('TRAE_RX', 'Trae RX'), ('TIPO_USO', 'Tipo de Uso'), ('ULTIMO_DIAGNOSTICO', 'Último Diagnóstico')], max_length=30, verbose_name='Tipo de Antecedente')),
                ('observacion', models.CharField(default='NIEGA', max_length=200, verbose_name='Observación')),
                ('examen_visual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_visuales', to='admision_recepcion.examenvisual')),
            ],
            options={
                'verbose_name': 'Antecedente Visual',
                'verbose_name_plural': 'Antecedentes Visuales',
                'unique_together': {('examen_visual', 'tipo_antecedente')},
            },
        ),
    ]
