# Generated by Django 4.2.23 on 2025-08-10 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admision_recepcion', '0010_evaluacionosteomuscular_recomendacionosteomuscular'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinicaGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evaluacion_medica', models.CharField(choices=[('PREOCUPACIONAL', 'Pre-ocupacional'), ('OCUPACIONAL', 'Ocupacional'), ('POSTOCUPACIONAL', 'Post-ocupacional'), ('CONSULTA_EXTERNA', 'Consulta Externa'), ('URGENCIAS', 'Urgencias')], default='CONSULTA_EXTERNA', max_length=20)),
                ('estado_civil', models.CharField(blank=True, choices=[('SOLTERO', 'Soltero/a'), ('CASADO', 'Casado/a'), ('UNION_LIBRE', 'Unión Libre'), ('SEPARADO', 'Separado/a'), ('DIVORCIADO', 'Divorciado/a'), ('VIUDO', 'Viudo/a')], max_length=15)),
                ('nivel_educativo', models.CharField(blank=True, choices=[('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('TECNICO', 'Técnico'), ('TECNOLOGICO', 'Tecnológico'), ('UNIVERSITARIO', 'Universitario'), ('POSTGRADO', 'Postgrado')], max_length=15)),
                ('eps', models.CharField(blank=True, max_length=100, verbose_name='EPS')),
                ('afp', models.CharField(blank=True, max_length=100, verbose_name='AFP')),
                ('arl', models.CharField(blank=True, max_length=100, verbose_name='ARL')),
                ('funciones_cargo', models.TextField(blank=True, verbose_name='Funciones del Cargo')),
                ('motivo_consulta', models.TextField(blank=True, verbose_name='Motivo de Consulta')),
                ('enfermedad_actual', models.TextField(blank=True, verbose_name='Enfermedad Actual')),
                ('tension_sistolica', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tensión Sistólica (mmHg)')),
                ('tension_diastolica', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tensión Diastólica (mmHg)')),
                ('clasificacion_ta', models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('PREHIPERTENSION', 'Prehipertensión'), ('HTA_GRADO_1', 'HTA Grado 1'), ('HTA_GRADO_2', 'HTA Grado 2'), ('CRISIS_HIPERTENSIVA', 'Crisis Hipertensiva')], max_length=20, verbose_name='Clasificación TA')),
                ('frecuencia_cardiaca', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Cardíaca (x min)')),
                ('frecuencia_respiratoria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Frecuencia Respiratoria (x min)')),
                ('pulsioximetria', models.PositiveIntegerField(blank=True, null=True, verbose_name='Pulsioximetría (%)')),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('lateralidad_dominante', models.CharField(choices=[('DIESTRO', 'Diestro'), ('ZURDO', 'Zurdo'), ('AMBIDIESTRO', 'Ambidiestro')], default='DIESTRO', max_length=12, verbose_name='Lateralidad Dominante')),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Talla (cm)')),
                ('imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='IMC')),
                ('perimetro_abdominal', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Perímetro Abdominal (cm)')),
                ('interpretacion_perimetro', models.CharField(blank=True, max_length=100, verbose_name='Interpretación Perímetro Abdominal')),
                ('revision_sistemas', models.JSONField(blank=True, default=dict, verbose_name='Revisión por Sistemas')),
                ('examen_fisico', models.JSONField(blank=True, default=dict, verbose_name='Examen Físico')),
                ('observaciones_paraclinicos', models.TextField(blank=True, verbose_name='Observaciones Paraclínicos')),
                ('via_ingreso', models.CharField(default='01', max_length=10, verbose_name='Vía de Ingreso')),
                ('finalidad_consulta', models.CharField(default='10', max_length=10, verbose_name='Finalidad de la Consulta')),
                ('causa_externa', models.CharField(default='15', max_length=10, verbose_name='Causa Externa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ficha_clinica', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica_general', to='admision_recepcion.fichaclinica')),
            ],
            options={
                'verbose_name': 'Historia Clínica General',
                'verbose_name_plural': 'Historias Clínicas Generales',
            },
        ),
        migrations.CreateModel(
            name='OrdenServicioGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.PositiveIntegerField(default=1, verbose_name='Número de Orden')),
                ('nombre_servicio', models.CharField(max_length=200, verbose_name='Nombre del Servicio')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_servicios', to='admision_recepcion.historiaclinicageneral')),
            ],
            options={
                'verbose_name': 'Orden de Servicio General',
                'verbose_name_plural': 'Órdenes de Servicios Generales',
            },
        ),
        migrations.CreateModel(
            name='OrdenRemision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.PositiveIntegerField(default=1, verbose_name='Número de Orden')),
                ('nombre_especialidad', models.CharField(max_length=100, verbose_name='Nombre de la Especialidad')),
                ('motivo_remision', models.TextField(verbose_name='Motivo de la Remisión')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_remisiones', to='admision_recepcion.historiaclinicageneral')),
            ],
            options={
                'verbose_name': 'Orden de Remisión',
                'verbose_name_plural': 'Órdenes de Remisiones',
            },
        ),
        migrations.CreateModel(
            name='OrdenMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.PositiveIntegerField(default=1, verbose_name='Número de Orden')),
                ('nombre_medicamento', models.CharField(max_length=200, verbose_name='Nombre del Medicamento')),
                ('cantidad', models.CharField(max_length=50, verbose_name='Cantidad')),
                ('posologia', models.CharField(max_length=200, verbose_name='Posología')),
                ('frecuencia', models.CharField(blank=True, max_length=100, verbose_name='Frecuencia')),
                ('dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Días')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_medicamentos', to='admision_recepcion.historiaclinicageneral')),
            ],
            options={
                'verbose_name': 'Orden de Medicamento',
                'verbose_name_plural': 'Órdenes de Medicamentos',
            },
        ),
        migrations.CreateModel(
            name='OrdenIncapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.PositiveIntegerField(default=1, verbose_name='Número de Orden')),
                ('motivo_incapacidad', models.TextField(verbose_name='Motivo de la Incapacidad')),
                ('dias', models.PositiveIntegerField(verbose_name='Días')),
                ('tipo', models.CharField(choices=[('ENFERMEDAD_GENERAL', 'Enfermedad General'), ('ACCIDENTE_TRABAJO', 'Accidente de Trabajo'), ('ENFERMEDAD_LABORAL', 'Enfermedad Laboral'), ('LICENCIA_MATERNIDAD', 'Licencia de Maternidad'), ('LICENCIA_PATERNIDAD', 'Licencia de Paternidad')], default='ENFERMEDAD_GENERAL', max_length=20, verbose_name='Tipo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_incapacidades', to='admision_recepcion.historiaclinicageneral')),
            ],
            options={
                'verbose_name': 'Orden de Incapacidad',
                'verbose_name_plural': 'Órdenes de Incapacidades',
            },
        ),
        migrations.CreateModel(
            name='EvolucionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('evolucion', models.TextField(verbose_name='Evolución')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evoluciones', to='admision_recepcion.historiaclinicageneral')),
                ('profesional_asistencial', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision_recepcion.prestador', verbose_name='Profesional Asistencial')),
            ],
            options={
                'verbose_name': 'Evolución General',
                'verbose_name_plural': 'Evoluciones Generales',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200, verbose_name='Nombre del Documento')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('archivo', models.FileField(blank=True, null=True, upload_to='documentos_clinicos/', verbose_name='Archivo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_clinicos', to='admision_recepcion.historiaclinicageneral')),
                ('usuario_creacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento Clínico',
                'verbose_name_plural': 'Documentos Clínicos',
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diagnostico', models.CharField(choices=[('PRINCIPAL', 'Principal'), ('RELACIONADO_1', 'Relacionado 1'), ('RELACIONADO_2', 'Relacionado 2'), ('RELACIONADO_3', 'Relacionado 3')], max_length=15, verbose_name='Tipo Diagnóstico')),
                ('codigo_cie10', models.CharField(blank=True, max_length=10, verbose_name='Código CIE-10')),
                ('nombre_diagnostico', models.CharField(max_length=500, verbose_name='Nombre del Diagnóstico')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('tipo_impresion', models.CharField(choices=[('CONFIRMADO', 'Confirmado'), ('IMPRESION_DIAGNOSTICA', 'Impresión Diagnóstica'), ('REPETICION', 'Repetición')], default='IMPRESION_DIAGNOSTICA', max_length=25, verbose_name='Tipo de Impresión')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='admision_recepcion.historiaclinicageneral')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='admision_recepcion.prestador')),
            ],
            options={
                'verbose_name': 'Diagnóstico General',
                'verbose_name_plural': 'Diagnósticos Generales',
            },
        ),
        migrations.CreateModel(
            name='CertificadoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_certificado', models.PositiveIntegerField(default=1, verbose_name='Número de Certificado')),
                ('descripcion_certificado', models.TextField(verbose_name='Descripción del Certificado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados_medicos', to='admision_recepcion.historiaclinicageneral')),
            ],
            options={
                'verbose_name': 'Certificado Médico',
                'verbose_name_plural': 'Certificados Médicos',
            },
        ),
        migrations.CreateModel(
            name='AntecedentePersonalGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_antecedente', models.CharField(choices=[('HTA', 'Hipertensión Arterial'), ('DIABETES', 'Diabetes'), ('ENF_RENAL', 'Enfermedad Renal'), ('ENF_ARTICULAR', 'Enfermedad Articular'), ('TBC', 'Tuberculosis'), ('VENEREAS', 'Enfermedades Venéreas'), ('SIND_CONVULSIVO', 'Síndrome Convulsivo'), ('INMUNOLOGICOS', 'Inmunológicos'), ('HOSPITALIZACIONES', 'Hospitalizaciones'), ('TOXICOS_ALERGICOS', 'Tóxicos Alérgicos'), ('TRAUMATICO', 'Traumático'), ('QUIRURGICOS', 'Quirúrgicos'), ('OTRO', 'Otro')], max_length=20, verbose_name='Antecedente')),
                ('observacion', models.TextField(default='NO REFIERE', verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_personales', to='admision_recepcion.historiaclinicageneral')),
            ],
            options={
                'verbose_name': 'Antecedente Personal General',
                'verbose_name_plural': 'Antecedentes Personales Generales',
            },
        ),
        migrations.CreateModel(
            name='AntecedenteFamiliarGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_antecedente', models.CharField(choices=[('HIPERTENSION_ARTERIAL', 'Hipertensión Arterial'), ('DIABETES', 'Diabetes'), ('CANCER', 'Cáncer'), ('OTROS', 'Otros')], max_length=30, verbose_name='Antecedente')),
                ('observacion', models.TextField(default='NO REFIERE', verbose_name='Observación')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('historia_clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedentes_familiares', to='admision_recepcion.historiaclinicageneral')),
            ],
            options={
                'verbose_name': 'Antecedente Familiar General',
                'verbose_name_plural': 'Antecedentes Familiares Generales',
            },
        ),
    ]
