# Generated by Django 4.2.23 on 2025-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_hospital', models.CharField(max_length=255, unique=True)),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('sitio_web', models.URLField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('mision', models.TextField(blank=True, null=True)),
                ('vision', models.TextField(blank=True, null=True)),
                ('valores', models.TextField(blank=True, null=True)),
                ('descripcion_corta', models.TextField(blank=True, null=True)),
                ('numero_habilitacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_habilitacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Perfil del Hospital',
                'verbose_name_plural': 'Perfiles del Hospital',
            },
        ),
    ]
