# Generated by Django 4.2.23 on 2025-07-12 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acs_hms_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificationBody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('acronym', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('is_accredited', models.BooleanField(default=True)),
                ('accreditation_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Certification Body',
                'verbose_name_plural': 'Certification Bodies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CertificationStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_certifications', models.IntegerField(default=0)),
                ('active_certifications', models.IntegerField(default=0)),
                ('expired_certifications', models.IntegerField(default=0)),
                ('expiring_soon', models.IntegerField(default=0)),
                ('medical_licenses', models.IntegerField(default=0)),
                ('specialty_certifications', models.IntegerField(default=0)),
                ('continuing_education', models.IntegerField(default=0)),
                ('renewals_processed', models.IntegerField(default=0)),
                ('renewals_pending', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Certification Statistics',
                'verbose_name_plural': 'Certification Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CertificationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('medical', 'Medical License'), ('specialty', 'Specialty Certification'), ('continuing_education', 'Continuing Education'), ('safety', 'Safety Certification'), ('quality', 'Quality Certification'), ('technology', 'Technology Certification'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('validity_period_months', models.IntegerField(default=12, help_text='Validity period in months')),
                ('renewal_required', models.BooleanField(default=True)),
                ('continuing_education_hours', models.IntegerField(default=0, help_text='Required CE hours for renewal')),
                ('is_active', models.BooleanField(default=True)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification_body', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_types', to='acs_hms_certification.certificationbody')),
            ],
            options={
                'verbose_name': 'Certification Type',
                'verbose_name_plural': 'Certification Types',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DoctorCertification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_number', models.CharField(max_length=100)),
                ('issue_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked'), ('pending_renewal', 'Pending Renewal')], default='active', max_length=20)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certifications/')),
                ('last_renewal_date', models.DateField(blank=True, null=True)),
                ('next_renewal_date', models.DateField(blank=True, null=True)),
                ('ce_hours_completed', models.IntegerField(default=0)),
                ('ce_hours_required', models.IntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_certifications', to='acs_hms_certification.certificationtype')),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='acs_hms_base.hmsuser')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_certifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Doctor Certification',
                'verbose_name_plural': 'Doctor Certifications',
                'ordering': ['-issue_date'],
                'unique_together': {('doctor', 'certification_type', 'certificate_number')},
            },
        ),
        migrations.CreateModel(
            name='ContinuingEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('education_type', models.CharField(choices=[('course', 'Course'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('webinar', 'Webinar'), ('other', 'Other')], max_length=20)),
                ('provider', models.CharField(max_length=200)),
                ('credit_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='continuing_education/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='continuing_education', to='acs_hms_base.hmsuser')),
            ],
            options={
                'verbose_name': 'Continuing Education',
                'verbose_name_plural': 'Continuing Education',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='CertificationRenewal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renewal_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('renewal_date', models.DateField()),
                ('new_expiry_date', models.DateField()),
                ('renewal_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('renewal_application', models.FileField(blank=True, null=True, upload_to='renewals/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_renewals', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_renewals', to=settings.AUTH_USER_MODEL)),
                ('doctor_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewals', to='acs_hms_certification.doctorcertification')),
            ],
            options={
                'verbose_name': 'Certification Renewal',
                'verbose_name_plural': 'Certification Renewals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('expiry_warning', 'Expiry Warning'), ('expired', 'Expired'), ('renewal_required', 'Renewal Required'), ('verification_required', 'Verification Required')], max_length=25)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='acs_hms_certification.doctorcertification')),
            ],
            options={
                'verbose_name': 'Certification Notification',
                'verbose_name_plural': 'Certification Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CertificationAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('verified', 'Verified'), ('renewed', 'Renewed'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('doctor_certification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='acs_hms_certification.doctorcertification')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certification Audit',
                'verbose_name_plural': 'Certification Audits',
                'ordering': ['-timestamp'],
            },
        ),
    ]
