# Generated by Django 4.2.23 on 2025-07-02 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_reporte', models.CharField(max_length=255)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_reporte', models.FileField(blank=True, null=True, upload_to='generated_reports/')),
                ('parametros_filtro', models.TextField(blank=True, help_text='JSON de los parámetros usados para generar el reporte', null=True)),
            ],
        ),
    ]
