# Generated by Django 4.2.23 on 2025-07-12 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acs_hms_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('procedure_name', models.CharField(blank=True, max_length=200)),
                ('procedure_date', models.DateField(blank=True, null=True)),
                ('form_data', models.JSONField(default=dict, help_text='Patient responses to form fields')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Signature'), ('signed', 'Signed'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('patient_signature', models.TextField(blank=True, help_text='Digital signature data')),
                ('patient_signed_at', models.DateTimeField(blank=True, null=True)),
                ('patient_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('guardian_signature', models.TextField(blank=True, help_text='Guardian digital signature')),
                ('guardian_signed_at', models.DateTimeField(blank=True, null=True)),
                ('guardian_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('witness_name', models.CharField(blank=True, max_length=200)),
                ('witness_signature', models.TextField(blank=True)),
                ('witness_signed_at', models.DateTimeField(blank=True, null=True)),
                ('witness_relationship', models.CharField(blank=True, max_length=100)),
                ('doctor_signature', models.TextField(blank=True)),
                ('doctor_signed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('revocation_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='acs_hms_base.hmsuser')),
                ('guardian', models.ForeignKey(blank=True, help_text='Guardian for minor patients', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_consent_forms', to='acs_hms_base.patient')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_forms', to='acs_hms_base.patient')),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_consents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Form',
                'verbose_name_plural': 'Consent Forms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentFormStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_forms', models.IntegerField(default=0)),
                ('signed_forms', models.IntegerField(default=0)),
                ('pending_forms', models.IntegerField(default=0)),
                ('expired_forms', models.IntegerField(default=0)),
                ('revoked_forms', models.IntegerField(default=0)),
                ('avg_time_to_sign', models.DurationField(blank=True, null=True)),
                ('completion_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consent Form Statistics',
                'verbose_name_plural': 'Consent Form Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ConsentFormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('form_type', models.CharField(choices=[('general', 'General Medical Consent'), ('surgery', 'Surgical Consent'), ('anesthesia', 'Anesthesia Consent'), ('blood_transfusion', 'Blood Transfusion Consent'), ('dental', 'Dental Procedure Consent'), ('pediatric', 'Pediatric Consent'), ('radiology', 'Radiology Consent'), ('telemedicine', 'Telemedicine Consent'), ('research', 'Research Participation Consent'), ('privacy', 'Privacy and Data Consent'), ('custom', 'Custom Consent Form')], max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish'), ('fr', 'French')], default='en', max_length=10)),
                ('description', models.TextField()),
                ('content', models.TextField(help_text='HTML content of the consent form')),
                ('form_fields', models.JSONField(default=dict, help_text='JSON configuration of form fields')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_witness', models.BooleanField(default=False)),
                ('requires_guardian', models.BooleanField(default=False)),
                ('expires_after_days', models.IntegerField(blank=True, help_text='Days after which consent expires (null = no expiration)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Form Template',
                'verbose_name_plural': 'Consent Form Templates',
                'ordering': ['form_type', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsentFormNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('signature_required', 'Signature Required'), ('expiring_soon', 'Expiring Soon'), ('expired', 'Expired'), ('revoked', 'Revoked'), ('completed', 'Completed')], max_length=20)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('recipient_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='acs_hms_consent_form.consentform')),
            ],
            options={
                'verbose_name': 'Consent Form Notification',
                'verbose_name_plural': 'Consent Form Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentFormDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('original', 'Original Form'), ('signed', 'Signed Form'), ('summary', 'Summary')], default='original', max_length=20)),
                ('file', models.FileField(upload_to='consent_forms/')),
                ('file_size', models.IntegerField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='acs_hms_consent_form.consentform')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Form Document',
                'verbose_name_plural': 'Consent Form Documents',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='ConsentFormConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_required', models.BooleanField(default=True)),
                ('allow_electronic_signature', models.BooleanField(default=True)),
                ('require_timestamp', models.BooleanField(default=True)),
                ('auto_send_notifications', models.BooleanField(default=True)),
                ('reminder_days_before_expiry', models.IntegerField(default=7)),
                ('require_ip_logging', models.BooleanField(default=True)),
                ('require_user_agent_logging', models.BooleanField(default=True)),
                ('auto_generate_pdf', models.BooleanField(default=True)),
                ('include_signatures_in_pdf', models.BooleanField(default=True)),
                ('track_consent_costs', models.BooleanField(default=False)),
                ('consent_processing_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Form Configuration',
                'verbose_name_plural': 'Consent Form Configurations',
            },
        ),
        migrations.CreateModel(
            name='ConsentFormAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('viewed', 'Viewed'), ('signed', 'Signed'), ('revoked', 'Revoked'), ('expired', 'Expired'), ('printed', 'Printed'), ('emailed', 'Emailed')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consent_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='acs_hms_consent_form.consentform')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consent Form Audit',
                'verbose_name_plural': 'Consent Form Audits',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='consentform',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='acs_hms_consent_form.consentformtemplate'),
        ),
    ]
