# Generated by Django 4.2.23 on 2025-08-10 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0002_expand_inventory_complete'),
        ('accounting', '0004_add_colombian_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('INGRESO', 'Ingreso'), ('RETIRO', 'Retiro'), ('AJUSTE', 'Ajuste'), ('CAMBIO_INICIAL', 'Cambio Inicial')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Movimiento de Caja',
                'verbose_name_plural': 'Movimientos de Caja',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PromocionesPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo_promocion', models.CharField(choices=[('PORCENTAJE', 'Descuento Porcentual'), ('VALOR_FIJO', 'Valor Fijo'), ('2X1', '2x1'), ('COMBO', 'Combo'), ('COMPRA_MINIMA', 'Descuento por Compra Mínima')], max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('monto_minimo_compra', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('activa', models.BooleanField(default=True)),
                ('limite_usos_total', models.IntegerField(default=0, help_text='0 = sin límite')),
                ('limite_usos_cliente', models.IntegerField(default=0, help_text='0 = sin límite')),
                ('usos_actuales', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Promoción POS',
                'verbose_name_plural': 'Promociones POS',
            },
        ),
        migrations.AlterModelOptions(
            name='caja',
            options={'ordering': ['codigo'], 'verbose_name': 'Caja Registradora', 'verbose_name_plural': 'Cajas Registradoras'},
        ),
        migrations.AlterModelOptions(
            name='lineaventapos',
            options={'ordering': ['numero_linea'], 'verbose_name': 'Línea Venta POS', 'verbose_name_plural': 'Líneas Venta POS'},
        ),
        migrations.AlterModelOptions(
            name='metodopagopos',
            options={'ordering': ['orden_visualizacion', 'nombre'], 'verbose_name': 'Método de Pago POS', 'verbose_name_plural': 'Métodos de Pago POS'},
        ),
        migrations.AlterModelOptions(
            name='puntoventa',
            options={'ordering': ['codigo'], 'verbose_name': 'Punto de Venta', 'verbose_name_plural': 'Puntos de Venta'},
        ),
        migrations.AlterModelOptions(
            name='sesioncaja',
            options={'ordering': ['-fecha_apertura'], 'verbose_name': 'Sesión de Caja', 'verbose_name_plural': 'Sesiones de Caja'},
        ),
        migrations.AlterModelOptions(
            name='ventapos',
            options={'ordering': ['-fecha'], 'verbose_name': 'Venta POS', 'verbose_name_plural': 'Ventas POS'},
        ),
        migrations.RenameField(
            model_name='sesioncaja',
            old_name='saldo_final',
            new_name='diferencia_final',
        ),
        migrations.RenameField(
            model_name='sesioncaja',
            old_name='saldo_inicial',
            new_name='diferencia_inicial',
        ),
        migrations.RenameField(
            model_name='ventapos',
            old_name='referencia',
            new_name='autorizacion_pago',
        ),
        migrations.AddField(
            model_name='caja',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caja',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='requiere_autorizacion_cierre',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_maximo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo máximo permitido', max_digits=15),
        ),
        migrations.AddField(
            model_name='caja',
            name='saldo_minimo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Saldo mínimo requerido para operar', max_digits=15),
        ),
        migrations.AddField(
            model_name='caja',
            name='ubicacion_fisica',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='usuarios_autorizados',
            field=models.ManyToManyField(blank=True, related_name='cajas_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='autorizado_descuento_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='descuentos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='cantidad_devuelta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='comentarios_vendedor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='descuento_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='fecha_devolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='impuesto_valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='motivo_descuento',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='motivo_devolucion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='numero_linea',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='numero_receta',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='porcentaje_impuesto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='precio_original',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio antes de descuentos', max_digits=16),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.producto'),
        ),
        migrations.AddField(
            model_name='lineaventapos',
            name='requiere_receta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='cuenta_comision',
            field=models.ForeignKey(blank=True, help_text='Cuenta para registrar comisiones', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metodos_pago_comision', to='accounting.cuentacontable'),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='dias_compensacion',
            field=models.IntegerField(default=0, help_text='Días para compensación del pago'),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='limite_maximo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Límite máximo por transacción (0 = sin límite)', max_digits=15),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='orden_visualizacion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='porcentaje_comision',
            field=models.DecimalField(decimal_places=4, default=0, help_text='Porcentaje de comisión', max_digits=5),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='requiere_autorizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='requiere_autorizacion_banco',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='requiere_pin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='requiere_referencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='tipo_metodo',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia Bancaria'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito'), ('VALE', 'Vale/Cupón'), ('MIXTO', 'Pago Mixto')], default='EFECTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='url_api',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='metodopagopos',
            name='valor_fijo_comision',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor fijo de comisión', max_digits=10),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='codigo',
            field=models.CharField(blank=True, help_text='Código del punto de venta', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='cuenta_ventas_default',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable por defecto para ventas', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta_ventas', to='accounting.cuentacontable'),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='descuento_maximo_permitido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='diario_ventas',
            field=models.ForeignKey(blank=True, help_text='Diario contable para las ventas de este POS', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='puntos_venta', to='accounting.diario'),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='impresora_tickets',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='imprimir_automatico',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='limite_credito_diario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='permite_ventas_credito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='requiere_autorizacion_descuentos',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='template_ticket',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='puntoventa',
            name='tipo_pos',
            field=models.CharField(choices=[('FARMACIA', 'Farmacia'), ('CAFETERIA', 'Cafetería'), ('TIENDA', 'Tienda'), ('SERVICIOS', 'Servicios Médicos'), ('LABORATORIO', 'Laboratorio'), ('GENERAL', 'General')], default='GENERAL', max_length=20),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='asiento_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_apertura', to='accounting.asientocontable'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='asiento_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_cierre', to='accounting.asientocontable'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='contabilizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='duracion_minutos',
            field=models.IntegerField(default=0, help_text='Duración de la sesión en minutos'),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='estado',
            field=models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada'), ('SUSPENDIDA', 'Suspendida'), ('CANCELADA', 'Cancelada')], default='ABIERTA', max_length=15),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='numero_clientes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='numero_sesion',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='numero_transacciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='observaciones_apertura',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='observaciones_cierre',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='saldo_final_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='saldo_final_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='saldo_inicial_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='saldo_inicial_sistema',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='supervisor_apertura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_supervisor_apertura', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='supervisor_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_supervisor_cierre', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_devoluciones',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_ingresos_extra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_retiros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_ventas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_ventas_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_ventas_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_ventas_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='sesioncaja',
            name='total_ventas_transferencia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='actualizo_inventario',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='asiento_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.asientocontable'),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='cambio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='codigo_promocion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='comentarios_internos',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='contabilizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='costo_domicilio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='descuento_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='direccion_entrega',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='email_cliente',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('PAGADA', 'Pagada'), ('DEVOLUCION_PARCIAL', 'Devolución Parcial'), ('DEVOLUCION_TOTAL', 'Devolución Total'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='fecha_confirmacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='fecha_prescripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='impuestos_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='medico_prescriptor',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='monto_recibido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='nombre_cliente',
            field=models.CharField(blank=True, help_text='Nombre del cliente si no está registrado', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='numero_prescripcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='numero_ticket',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='requiere_seguimiento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_supervisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='telefono_cliente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='tipo_venta',
            field=models.CharField(choices=[('MOSTRADOR', 'Venta Mostrador'), ('DOMICILIO', 'Venta Domicilio'), ('TELEFONICA', 'Venta Telefónica'), ('ONLINE', 'Venta Online'), ('PRESCRIPCION', 'Venta con Prescripción')], default='MOSTRADOR', max_length=20),
        ),
        migrations.AddField(
            model_name='ventapos',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='caja',
            name='cuenta_contable',
            field=models.ForeignKey(help_text='Cuenta contable para el efectivo de esta caja', on_delete=django.db.models.deletion.PROTECT, to='accounting.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='caja',
            name='punto_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cajas', to='pos.puntoventa'),
        ),
        migrations.AlterField(
            model_name='lineaventapos',
            name='impuesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.impuesto'),
        ),
        migrations.AlterField(
            model_name='lineaventapos',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='lineaventapos',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AlterField(
            model_name='metodopagopos',
            name='cuenta_contable',
            field=models.ForeignKey(help_text='Cuenta contable para este método de pago', on_delete=django.db.models.deletion.PROTECT, to='accounting.cuentacontable'),
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='caja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='pos.caja'),
        ),
        migrations.AlterField(
            model_name='sesioncaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sesiones_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ventapos',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='pos.sesioncaja'),
        ),
        migrations.AlterUniqueTogether(
            name='lineaventapos',
            unique_together={('venta', 'numero_linea')},
        ),
        migrations.AddIndex(
            model_name='ventapos',
            index=models.Index(fields=['numero_ticket'], name='pos_ventapo_numero__04c080_idx'),
        ),
        migrations.AddIndex(
            model_name='ventapos',
            index=models.Index(fields=['fecha', 'sesion'], name='pos_ventapo_fecha_199cfa_idx'),
        ),
        migrations.AddIndex(
            model_name='ventapos',
            index=models.Index(fields=['estado'], name='pos_ventapo_estado_3a9d4a_idx'),
        ),
        migrations.AddIndex(
            model_name='ventapos',
            index=models.Index(fields=['tercero'], name='pos_ventapo_tercero_b85086_idx'),
        ),
        migrations.AddField(
            model_name='promocionespos',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='inventories.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='promocionespos',
            name='productos',
            field=models.ManyToManyField(blank=True, to='inventories.producto'),
        ),
        migrations.AddField(
            model_name='promocionespos',
            name='puntos_venta',
            field=models.ManyToManyField(blank=True, to='pos.puntoventa'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_caja_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_caja', to='pos.sesioncaja'),
        ),
        migrations.AddField(
            model_name='movimientocaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
