# Generated by Django 4.2.23 on 2025-07-12 06:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('acs_hms_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('doctor', 'Doctor'), ('referrer', 'Referrer'), ('employee', 'Employee'), ('partner', 'Partner'), ('external', 'External Agent')], max_length=20)),
                ('agent_code', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('account_number', models.CharField(blank=True, max_length=50)),
                ('routing_number', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('commission_threshold', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum commission amount before payout', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commission Agent',
                'verbose_name_plural': 'Commission Agents',
                'ordering': ['agent_code'],
            },
        ),
        migrations.CreateModel(
            name='CommissionStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('consultation', 'Consultation'), ('procedure', 'Procedure'), ('surgery', 'Surgery'), ('test', 'Diagnostic Test'), ('referral', 'Referral'), ('prescription', 'Prescription'), ('other', 'Other')], max_length=20)),
                ('calculation_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat_fee', 'Flat Fee'), ('tiered', 'Tiered Structure'), ('custom', 'Custom Formula')], max_length=20)),
                ('percentage_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('flat_fee_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tier_structure', models.JSONField(default=dict, help_text='JSON structure for tiered commissions')),
                ('custom_formula', models.TextField(blank=True, help_text='Custom formula for commission calculation')),
                ('minimum_service_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum service amount to qualify for commission', max_digits=10)),
                ('maximum_commission', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum commission amount (null = no limit)', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_date', models.DateField(default=django.utils.timezone.now)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_structures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Structure',
                'verbose_name_plural': 'Commission Structures',
                'ordering': ['service_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('report_type', models.CharField(choices=[('monthly', 'Monthly Report'), ('quarterly', 'Quarterly Report'), ('annual', 'Annual Report'), ('custom', 'Custom Report')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('report_data', models.JSONField(default=dict)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='commission_reports/')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('agent_filter', models.ManyToManyField(blank=True, to='acs_hms_commission.commissionagent')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_reports', to=settings.AUTH_USER_MODEL)),
                ('structure_filter', models.ManyToManyField(blank=True, to='acs_hms_commission.commissionstructure')),
            ],
            options={
                'verbose_name': 'Commission Report',
                'verbose_name_plural': 'Commission Reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('service_description', models.TextField()),
                ('service_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('service_date', models.DateField()),
                ('commission_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_details', models.JSONField(default=dict, help_text='Details of commission calculation')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='acs_hms_commission.commissionagent')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_commissions', to=settings.AUTH_USER_MODEL)),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.asientocontable')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_commissions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='acs_hms_base.patient')),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_records', to='acs_hms_commission.commissionstructure')),
            ],
            options={
                'verbose_name': 'Commission Record',
                'verbose_name_plural': 'Commission Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(editable=False, max_length=100, unique=True)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('bank_transfer', 'Bank Transfer'), ('check', 'Check'), ('cash', 'Cash'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20)),
                ('payment_date', models.DateField()),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='acs_hms_commission.commissionagent')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.asientocontable')),
                ('commission_records', models.ManyToManyField(related_name='payments', to='acs_hms_commission.commissionrecord')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_payments', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Payment',
                'verbose_name_plural': 'Commission Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommissionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_approve_under_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Auto-approve commissions under this amount', max_digits=10)),
                ('minimum_payment_amount', models.DecimalField(decimal_places=2, default=100.0, help_text='Minimum amount for batch payments', max_digits=10)),
                ('payment_frequency_days', models.IntegerField(default=30, help_text='Payment frequency in days')),
                ('notify_on_commission_earned', models.BooleanField(default=True)),
                ('notify_on_payment_processed', models.BooleanField(default=True)),
                ('default_commission_account', models.CharField(default='6200', help_text='Default account code for commission expenses', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Commission Configuration',
                'verbose_name_plural': 'Commission Configurations',
            },
        ),
        migrations.AddField(
            model_name='commissionagent',
            name='default_commission_structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_agents', to='acs_hms_commission.commissionstructure'),
        ),
        migrations.AddField(
            model_name='commissionagent',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission_agent', to=settings.AUTH_USER_MODEL),
        ),
    ]
