# Generated by Django 4.2.23 on 2025-07-02 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categorías de Producto',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenDispensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UbicacionAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_producto', models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('INSUMO', 'Insumo'), ('EQUIPO', 'Equipo')], max_length=20)),
                ('unidad_medida', models.CharField(help_text='Ej: mg, ml, unidades, cajas', max_length=50)),
                ('stock_actual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Alerta cuando el stock es inferior a este valor', max_digits=10)),
                ('fecha_caducidad', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventories.categoriaproducto')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventories.ubicacionalmacen')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenDispensacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_dispensacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_dispensacion', to='patients.paciente')),
                ('productos', models.ManyToManyField(through='inventories.DetalleOrdenDispensacion', to='inventories.producto')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE', 'Ajuste')], max_length=10)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('razon', models.TextField(blank=True, null=True)),
                ('referencia_documento', models.CharField(blank=True, max_length=100, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventories.producto')),
            ],
        ),
        migrations.AddField(
            model_name='detalleordendispensacion',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.ordendispensacion'),
        ),
        migrations.AddField(
            model_name='detalleordendispensacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.producto'),
        ),
    ]
