# Generated by Django 4.2.23 on 2025-08-10 04:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_add_colombian_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock_fisico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valor_diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('fecha_conteo', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('ajustado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Detalle Inventario Físico',
                'verbose_name_plural': 'Detalles Inventario Físico',
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('impuesto_valor', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_linea', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle Orden de Compra',
                'verbose_name_plural': 'Detalles Orden de Compra',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcionMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Detalle Recepción',
                'verbose_name_plural': 'Detalles Recepción',
            },
        ),
        migrations.CreateModel(
            name='InventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_planificada', models.DateField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('AJUSTADO', 'Ajustado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=15)),
                ('tipos_producto', models.CharField(blank=True, help_text='Tipos de producto separados por coma', max_length=500, null=True)),
                ('total_productos_contados', models.IntegerField(default=0)),
                ('total_diferencias', models.IntegerField(default=0)),
                ('valor_diferencias', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Inventario Físico',
                'verbose_name_plural': 'Inventarios Físicos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(help_text='Número de orden de compra', max_length=50, unique=True)),
                ('fecha_orden', models.DateField(default=django.utils.timezone.now)),
                ('fecha_entrega_esperada', models.DateField(blank=True, null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('CONFIRMADA', 'Confirmada'), ('RECIBIDA', 'Recibida'), ('FACTURADA', 'Facturada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('contabilizada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Orden de Compra',
                'verbose_name_plural': 'Órdenes de Compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='RecepcionMercancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('fecha_recepcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('numero_remision', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcial'), ('COMPLETA', 'Completa'), ('CERRADA', 'Cerrada')], default='PENDIENTE', max_length=15)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('inspeccion_realizada', models.BooleanField(default=False)),
                ('inspeccion_aprobada', models.BooleanField(default=False)),
                ('observaciones_inspeccion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Recepción de Mercancía',
                'verbose_name_plural': 'Recepciones de Mercancía',
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha_hora'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['codigo', 'nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.RenameField(
            model_name='movimientoinventario',
            old_name='razon',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='asiento_contable',
            field=models.ForeignKey(blank=True, help_text='Asiento contable generado por este movimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.asientocontable'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_autorizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='contabilizado',
            field=models.BooleanField(default=False, help_text='Si ya se generó el asiento contable'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('CONFIRMADO', 'Confirmado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=15),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='fecha_documento',
            field=models.DateField(blank=True, help_text='Fecha del documento origen', null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='numero_documento',
            field=models.CharField(blank=True, help_text='Número del documento origen', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio unitario del movimiento', max_digits=15),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor en caso de entrada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to='accounting.tercero'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='requiere_contabilizacion',
            field=models.BooleanField(default=True, help_text='Si requiere generar asiento contable'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_anterior',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock antes del movimiento', max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_nuevo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock después del movimiento', max_digits=10),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='ubicacion_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_destino', to='inventories.ubicacionalmacen'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='ubicacion_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_origen', to='inventories.ubicacionalmacen'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total del movimiento', max_digits=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default=1, help_text='Código interno del producto', max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo_barras',
            field=models.CharField(blank=True, help_text='Código de barras', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='controlado',
            field=models.BooleanField(default=False, help_text='Producto controlado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta_costo_venta',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para el costo de venta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_costo_venta', to='accounting.cuentacontable'),
        ),
        migrations.AddField(
            model_name='producto',
            name='cuenta_inventario',
            field=models.ForeignKey(blank=True, help_text='Cuenta contable para el inventario del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_inventario', to='accounting.cuentacontable'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('DESCONTINUADO', 'Descontinuado'), ('AGOTADO', 'Agotado'), ('BLOQUEADO', 'Bloqueado')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='margen_ganancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Margen de ganancia en %', max_digits=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='modificado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_modificados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Peso en gramos', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra unitario', max_digits=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta unitario', max_digits=15),
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor_principal',
            field=models.ForeignKey(blank=True, help_text='Proveedor principal del producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_suministrados', to='accounting.tercero'),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_prescripcion',
            field=models.BooleanField(default=False, help_text='Requiere prescripción médica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stock máximo recomendado', max_digits=10),
        ),
        migrations.AddField(
            model_name='producto',
            name='volumen',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Volumen en ml', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo_movimiento',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('TRANSFERENCIA', 'Transferencia'), ('DEVOLUCION', 'Devolución'), ('MERMA', 'Merma'), ('VENCIMIENTO', 'Vencimiento')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('MEDICAMENTO', 'Medicamento'), ('INSUMO', 'Insumo Médico'), ('EQUIPO', 'Equipo Médico'), ('DISPOSITIVO', 'Dispositivo Médico'), ('MATERIAL', 'Material de Oficina'), ('CONSUMIBLE', 'Consumible')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['producto', 'tipo_movimiento'], name='inventories_product_9abdbe_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['fecha_hora'], name='inventories_fecha_h_fdd04f_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['numero_documento'], name='inventories_numero__7c031b_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientoinventario',
            index=models.Index(fields=['estado'], name='inventories_estado_2120c9_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo'], name='inventories_codigo_7a1305_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['codigo_barras'], name='inventories_codigo__51edcb_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['tipo_producto'], name='inventories_tipo_pr_136a03_idx'),
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['estado'], name='inventories_estado_074559_idx'),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='inspeccionado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspecciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones', to='inventories.ordencompra'),
        ),
        migrations.AddField(
            model_name='recepcionmercancia',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='asiento_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.asientocontable'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='autorizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_compra_inventario_autorizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordenes_compra', to='accounting.tercero'),
        ),
        migrations.AddField(
            model_name='inventariofisico',
            name='categorias',
            field=models.ManyToManyField(blank=True, to='inventories.categoriaproducto'),
        ),
        migrations.AddField(
            model_name='inventariofisico',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inventariofisico',
            name='ubicaciones',
            field=models.ManyToManyField(blank=True, to='inventories.ubicacionalmacen'),
        ),
        migrations.AddField(
            model_name='detallerecepcionmercancia',
            name='detalle_orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.detalleordencompra'),
        ),
        migrations.AddField(
            model_name='detallerecepcionmercancia',
            name='recepcion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventories.recepcionmercancia'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='orden',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventories.ordencompra'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.producto'),
        ),
        migrations.AddField(
            model_name='detalleinventariofisico',
            name='contado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='detalleinventariofisico',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventories.inventariofisico'),
        ),
        migrations.AddField(
            model_name='detalleinventariofisico',
            name='movimiento_ajuste',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventories.movimientoinventario'),
        ),
        migrations.AddField(
            model_name='detalleinventariofisico',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventories.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleinventariofisico',
            unique_together={('inventario', 'producto')},
        ),
    ]
