# Generated by Django 4.2.23 on 2025-07-12 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acs_hms_base', '0001_initial'),
        ('acs_hms_operation_theater', '0001_initial'),
        ('acs_hms_surgery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theaterutilization',
            name='operation_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='utilizations', to='acs_hms_surgery.operationtheater'),
        ),
        migrations.AddField(
            model_name='theaterstaff',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_staff_assignments', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterstaff',
            name='operation_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='acs_hms_surgery.operationtheater'),
        ),
        migrations.AddField(
            model_name='theaterstaff',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_staff', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterschedule',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_schedules', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterschedule',
            name='operation_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='acs_hms_surgery.operationtheater'),
        ),
        migrations.AddField(
            model_name='theaterpreparation',
            name='assigned_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_preparations', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterpreparation',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparations', to='acs_hms_operation_theater.theaterbooking'),
        ),
        migrations.AddField(
            model_name='theaterpreparation',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_preparations', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterinventory',
            name='operation_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='acs_hms_surgery.operationtheater'),
        ),
        migrations.AddField(
            model_name='theaterincident',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='acs_hms_operation_theater.theaterbooking'),
        ),
        migrations.AddField(
            model_name='theaterincident',
            name='investigated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_incidents', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterincident',
            name='operation_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='acs_hms_surgery.operationtheater'),
        ),
        migrations.AddField(
            model_name='theaterincident',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_incidents', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterequipmentchecklist',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_checklists', to='acs_hms_operation_theater.theaterbooking'),
        ),
        migrations.AddField(
            model_name='theaterequipmentchecklist',
            name='checked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_checklists', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterbooking',
            name='booked_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theater_bookings', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterbooking',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_bookings', to='acs_hms_base.hmsuser'),
        ),
        migrations.AddField(
            model_name='theaterbooking',
            name='operation_theater',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='acs_hms_surgery.operationtheater'),
        ),
        migrations.AddField(
            model_name='theaterbooking',
            name='surgery',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theater_booking', to='acs_hms_surgery.surgery'),
        ),
        migrations.AlterUniqueTogether(
            name='theaterutilization',
            unique_together={('operation_theater', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='theaterschedule',
            unique_together={('operation_theater', 'date', 'start_time')},
        ),
    ]
