# Generated by Django 4.2.23 on 2025-07-12 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acs_hms_base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingScreen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('screen_type', models.CharField(choices=[('general', 'General Waiting Area'), ('department', 'Department Specific'), ('doctor', 'Doctor Specific'), ('emergency', 'Emergency')], max_length=20)),
                ('location', models.CharField(max_length=200)),
                ('display_queue', models.BooleanField(default=True)),
                ('display_announcements', models.BooleanField(default=True)),
                ('display_health_tips', models.BooleanField(default=True)),
                ('display_weather', models.BooleanField(default=False)),
                ('refresh_interval', models.IntegerField(default=30, help_text='Refresh interval in seconds')),
                ('theme_color', models.CharField(default='#007bff', max_length=7)),
                ('logo_file', models.FileField(blank=True, null=True, upload_to='waiting_screens/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Waiting Screen',
                'verbose_name_plural': 'Waiting Screens',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WaitingQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_number', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('arrival_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('called_time', models.DateTimeField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_minutes', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'user_type': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='waiting_queues', to='acs_hms_base.hmsuser')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiting_queues', to='acs_hms_base.patient')),
                ('screen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='acs_hms_waiting_screen.waitingscreen')),
            ],
            options={
                'verbose_name': 'Waiting Queue',
                'verbose_name_plural': 'Waiting Queues',
                'ordering': ['arrival_time'],
            },
        ),
        migrations.CreateModel(
            name='ScreenConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_refresh_interval', models.IntegerField(default=30)),
                ('default_theme_color', models.CharField(default='#007bff', max_length=7)),
                ('show_queue_numbers', models.BooleanField(default=True)),
                ('show_wait_times', models.BooleanField(default=True)),
                ('show_doctor_names', models.BooleanField(default=True)),
                ('enable_audio_announcements', models.BooleanField(default=True)),
                ('audio_language', models.CharField(default='en', max_length=10)),
                ('health_tips_interval', models.IntegerField(default=60, help_text='Interval in seconds')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Screen Configuration',
                'verbose_name_plural': 'Screen Configurations',
            },
        ),
        migrations.CreateModel(
            name='ScreenAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('announcement_type', models.CharField(choices=[('general', 'General'), ('emergency', 'Emergency'), ('maintenance', 'Maintenance'), ('health_tip', 'Health Tip')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(default=1, help_text='Higher numbers = higher priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screen_announcements', to=settings.AUTH_USER_MODEL)),
                ('screens', models.ManyToManyField(related_name='announcements', to='acs_hms_waiting_screen.waitingscreen')),
            ],
            options={
                'verbose_name': 'Screen Announcement',
                'verbose_name_plural': 'Screen Announcements',
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('general', 'General Health'), ('nutrition', 'Nutrition'), ('exercise', 'Exercise'), ('mental_health', 'Mental Health'), ('preventive', 'Preventive Care'), ('seasonal', 'Seasonal Health')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Health Tip',
                'verbose_name_plural': 'Health Tips',
                'ordering': ['-created_at'],
            },
        ),
    ]
