# Generated by Django 4.2.23 on 2025-07-02 05:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código PUC', max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('ORDEN', 'Orden')], max_length=20)),
                ('nivel', models.IntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='accounting.cuentacontable')),
            ],
        ),
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('CAJA', 'Caja'), ('BANCO', 'Banco'), ('VENTAS', 'Ventas'), ('COMPRAS', 'Compras')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Impuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('IVA', 'IVA'), ('ICA', 'ICA'), ('RETENCION', 'Retención'), ('OTRO', 'Otro')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PeriodoContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tercero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NATURAL', 'Persona Natural'), ('JURIDICA', 'Persona Jurídica')], max_length=10)),
                ('nombre', models.CharField(max_length=255)),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LineaAsiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('debito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='accounting.asientocontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.cuentacontable')),
                ('impuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.impuesto')),
                ('tercero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.tercero')),
            ],
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.diario'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.periodocontable'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='tercero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.tercero'),
        ),
    ]
