# Generated by Django 4.2.7 on 2025-07-29 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_add_new_accounting_features'),
        ('accounting', '0002_centrocosto_datosempresa_comprobantecontable_and_more'),
    ]

    operations = [
    ]
