# Generated by Django 4.2.23 on 2025-08-10 02:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_merge_20250728_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código ISO del país', max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='cuentacontable',
            options={'ordering': ['codigo'], 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Cuentas Contables'},
        ),
        migrations.AlterModelOptions(
            name='impuesto',
            options={'ordering': ['codigo'], 'verbose_name': 'Impuesto', 'verbose_name_plural': 'Impuestos'},
        ),
        migrations.AlterModelOptions(
            name='tercero',
            options={'ordering': ['nombre'], 'verbose_name': 'Tercero', 'verbose_name_plural': 'Terceros'},
        ),
        migrations.AddField(
            model_name='impuesto',
            name='fin_vigencia',
            field=models.DateField(blank=True, help_text='Fecha de fin de vigencia', null=True),
        ),
        migrations.AddField(
            model_name='impuesto',
            name='inicio_vigencia',
            field=models.DateField(blank=True, help_text='Fecha de inicio de vigencia', null=True),
        ),
        migrations.AddField(
            model_name='impuesto',
            name='valor_base_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo_presupuesto',
            field=models.CharField(blank=True, choices=[('INGRESO', 'Presupuesto de Ingresos'), ('GASTO', 'Presupuesto de Gastos'), ('INVERSION', 'Presupuesto de Inversión')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='codigo_tercero',
            field=models.CharField(blank=True, help_text='13=Natural, 31=Jurídica', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='cupo_credito',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=16, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='primer_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='primer_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='razon_social',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='regimen_iva',
            field=models.CharField(blank=True, choices=[('SIMPLIFICADO', 'Régimen Simplificado'), ('COMUN', 'Régimen Común'), ('GRAN_CONTRIBUYENTE', 'Gran Contribuyente'), ('NO_RESPONSABLE', 'No Responsable de IVA')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='responsable_ica',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tercero',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tercero',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cuentacontable',
            name='tipo',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('PASIVO', 'Pasivo'), ('PATRIMONIO', 'Patrimonio'), ('INGRESO', 'Ingreso'), ('GASTO', 'Gasto'), ('COSTO', 'Costo'), ('ORDEN', 'Cuentas de Orden')], max_length=20),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje del impuesto', max_digits=5),
        ),
        migrations.AlterField(
            model_name='impuesto',
            name='tipo',
            field=models.CharField(choices=[('IVA', 'IVA - Impuesto al Valor Agregado'), ('RETEICA', 'RETEICA - Retención de Industria y Comercio'), ('RETEFUENTE', 'RETEFUENTE - Retención en la Fuente'), ('RETEIVA', 'RETEIVA - Retención de IVA'), ('CONSUMO', 'Impuesto al Consumo'), ('OTRO', 'Otro Impuesto')], max_length=20),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_fin',
            field=models.DateField(blank=True, help_text='Dejar vacío para período indefinido', null=True),
        ),
        migrations.CreateModel(
            name='ReporteFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IVA', 'Declaración de IVA'), ('RETENCION', 'Retenciones en la Fuente'), ('ICA', 'Impuesto de Industria y Comercio'), ('RENTA', 'Declaración de Renta')], max_length=20)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('base_gravable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuesto_generado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuesto_descontable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('impuesto_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('GENERADO', 'Generado'), ('ENVIADO', 'Enviado'), ('APROBADO', 'Aprobado')], default='BORRADOR', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.periodocontable')),
            ],
            options={
                'verbose_name': 'Reporte Fiscal',
                'verbose_name_plural': 'Reportes Fiscales',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleFiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=200)),
                ('base_gravable', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('porcentaje_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.asientocontable')),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='accounting.reportefiscal')),
                ('tercero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.tercero')),
            ],
            options={
                'verbose_name': 'Detalle Fiscal',
                'verbose_name_plural': 'Detalles Fiscales',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código DANE del departamento', max_length=5, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='accounting.pais')),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código DANE de la ciudad', max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='accounting.departamento')),
            ],
            options={
                'verbose_name': 'Ciudad',
                'verbose_name_plural': 'Ciudades',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='tercero',
            name='ciudad_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.ciudad'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.departamento'),
        ),
        migrations.AddField(
            model_name='tercero',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.pais'),
        ),
    ]
