# Generated by Django 4.2.23 on 2025-07-12 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acs_hms_emergency', '0001_initial'),
    ]

    operations = [
    ]
