# Generated by Django 4.2.23 on 2025-08-10 06:15

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_cliente', models.CharField(choices=[('PACIENTE', 'Paciente'), ('SEGURO', 'Seguro'), ('EMPRESA', 'Empresa'), ('GUBERNAMENTAL', 'Gubernamental'), ('OTRO', 'Otro')], default='PACIENTE', max_length=20)),
                ('identificacion', models.CharField(max_length=50, unique=True)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contacto_principal', models.CharField(blank=True, max_length=100)),
                ('limite_credito', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_actual', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha_emision', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_vencimiento', models.DateField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDA', 'Emitida'), ('PAGADA', 'Pagada'), ('ANULADA', 'Anulada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='sales.cliente')),
            ],
            options={
                'verbose_name': 'Factura de Venta',
                'verbose_name_plural': 'Facturas de Venta',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('PRODUCTO', 'Producto'), ('SERVICIO', 'Servicio'), ('PROCEDIMIENTO', 'Procedimiento')], default='SERVICIO', max_length=20)),
                ('categoria', models.CharField(choices=[('MEDICAMENTOS', 'Medicamentos'), ('EQUIPOS', 'Equipos Médicos'), ('CONSULTAS', 'Consultas'), ('PROCEDIMIENTOS', 'Procedimientos'), ('LABORATORIO', 'Laboratorio'), ('IMAGENES', 'Imágenes'), ('OTROS', 'Otros')], default='OTROS', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('precio_especial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('requiere_autorizacion', models.BooleanField(default=False)),
                ('stock_disponible', models.IntegerField(default=0)),
                ('stock_minimo', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto/Servicio',
                'verbose_name_plural': 'Productos/Servicios',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PagoVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('CREDITO', 'Crédito')], max_length=20)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='sales.facturaventa')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Venta',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='OrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=20, unique=True)),
                ('fecha_orden', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_entrega_esperada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('CONFIRMADA', 'Confirmada'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADA', 'Completada'), ('CANCELADA', 'Cancelada')], default='BORRADOR', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('impuestos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_venta', to='sales.cliente')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_vendidas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Orden de Venta',
                'verbose_name_plural': 'Órdenes de Venta',
                'ordering': ['-fecha_orden'],
            },
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='orden_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='sales.ordenventa'),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_vendidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('SOLICITADA', 'Solicitada'), ('APROBADA', 'Aprobada'), ('PROCESADA', 'Procesada'), ('RECHAZADA', 'Rechazada')], default='SOLICITADA', max_length=20)),
                ('motivo', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='sales.facturaventa')),
                ('procesado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución de Venta',
                'verbose_name_plural': 'Devoluciones de Venta',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleOrdenVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.ordenventa')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.productoservicio')),
            ],
            options={
                'verbose_name': 'Detalle de Orden de Venta',
                'verbose_name_plural': 'Detalles de Órdenes de Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleFacturaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.facturaventa')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.productoservicio')),
            ],
            options={
                'verbose_name': 'Detalle de Factura de Venta',
                'verbose_name_plural': 'Detalles de Facturas de Venta',
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_devuelta', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField(blank=True)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.devolucionventa')),
                ('producto_servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.productoservicio')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devoluciones',
            },
        ),
    ]
